ALTER TYPE "AbsenceStatus" ADD VALUE IF NOT EXISTS 'ACKNOWLEDGED';
ALTER TYPE "AbsenceStatus" ADD VALUE IF NOT EXISTS 'CANCELED';
ALTER TYPE "AbsenceStatus" ADD VALUE IF NOT EXISTS 'ENDED';

ALTER TABLE "staff_absences"
  ALTER COLUMN "endDate" DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'Autre',
  ADD COLUMN IF NOT EXISTS "message" TEXT,
  ADD COLUMN IF NOT EXISTS "isIndefinite" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "superiorUserId" TEXT,
  ADD COLUMN IF NOT EXISTS "superiorNotifiedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "decidedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "endedByUserId" TEXT,
  ADD COLUMN IF NOT EXISTS "endedAt" TIMESTAMP(3);
