import path from 'node:path';
import { config as loadEnv } from 'dotenv';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

loadEnv({ path: path.resolve(import.meta.dir, '../../.env') });
loadEnv({ path: path.resolve(import.meta.dir, '../../../.env') });

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error('❌ DATABASE_URL non défini dans .env');
  process.exit(1);
}

const adapter = new PrismaPg({ connectionString });

const prisma = new PrismaClient({ adapter });

const GUILD_ID = process.env.GUILD_ID;
if (!GUILD_ID) {
  console.error('❌ GUILD_ID non défini dans .env');
  process.exit(1);
}

const guildId: string = GUILD_ID;

const DEFAULT_FEEDS = [
  // 🇫🇷 Actualité Tech Générale (France)
  { name: 'Presse-Citron', url: 'https://www.presse-citron.net/feed/', category: 'Actualité Tech Générale (France)', language: 'fr' },
  { name: 'Le Journal du Geek', url: 'https://www.journaldugeek.com/feed/', category: 'Actualité Tech Générale (France)', language: 'fr' },
  { name: 'Numerama', url: 'https://www.numerama.com/feed/', category: 'Actualité Tech Générale (France)', language: 'fr' },
  { name: 'Next (ex-Next INpact)', url: 'https://next.ink/feed/', category: 'Actualité Tech Générale (France)', language: 'fr' },
  { name: "L'Usine Digitale", url: 'https://www.usine-digitale.fr/rss', category: 'Actualité Tech Générale (France)', language: 'fr' },

  // 🌍 Références Internationales (Anglais)
  { name: 'The Verge', url: 'https://www.theverge.com/rss/index.xml', category: 'Références Internationales (Anglais)', language: 'en' },
  { name: 'TechCrunch', url: 'https://techcrunch.com/feed/', category: 'Références Internationales (Anglais)', language: 'en' },
  { name: 'Ars Technica', url: 'http://feeds.arstechnica.com/arstechnica/index', category: 'Références Internationales (Anglais)', language: 'en' },
  { name: 'Wired', url: 'https://www.wired.com/feed/rss', category: 'Références Internationales (Anglais)', language: 'en' },
  { name: 'Hacker News (Top)', url: 'https://hnrss.org/frontpage', category: 'Références Internationales (Anglais)', language: 'en' },

  // 🛡️ Cybersécurité & Open Source
  { name: 'Korben', url: 'https://korben.info/feed', category: 'Cybersécurité & Open Source', language: 'fr' },
  { name: 'CERT-FR (ANSSI)', url: 'https://www.cert.ssi.gouv.fr/feed/', category: 'Cybersécurité & Open Source', language: 'fr' },
  { name: 'CNIL (Actus)', url: 'https://www.cnil.fr/fr/rss.xml', category: 'Cybersécurité & Open Source', language: 'fr' },
  { name: 'The Hacker News', url: 'https://feeds.feedburner.com/TheHackersNews', category: 'Cybersécurité & Open Source', language: 'en' },

  // 🤖 Intelligence Artificielle & Dev
  { name: 'OpenAI Blog', url: 'https://openai.com/blog/rss.xml', category: 'Intelligence Artificielle & Dev', language: 'en' },
  { name: 'Google News (AI)', url: 'https://news.google.com/rss/search?q=Artificial+Intelligence', category: 'Intelligence Artificielle & Dev', language: 'en' },
  { name: 'Baeldung (Dev)', url: 'https://www.baeldung.com/feed', category: 'Intelligence Artificielle & Dev', language: 'en' },
  { name: 'GitHub Blog', url: 'https://github.blog/feed/', category: 'Intelligence Artificielle & Dev', language: 'en' },

  // 💻 Hardware & Gaming
  { name: "Tom's Hardware France", url: 'https://www.tomshardware.fr/feed/', category: 'Hardware & Gaming', language: 'fr' },
  { name: 'Comptoir du Hardware', url: 'http://www.comptoir-hardware.com/home.xml', category: 'Hardware & Gaming', language: 'fr' },
  { name: 'Frandroid', url: 'https://www.frandroid.com/feed', category: 'Hardware & Gaming', language: 'fr' },
  { name: 'Eurogamer', url: 'https://www.eurogamer.net/feed/news', category: 'Hardware & Gaming', language: 'en' },
];

const DEFAULT_DEVELOPER_EXCUSES = [
  'Ça fonctionnait sur ma machine.',
  "C'est un problème de cache.",
  "C'est une fonctionnalité, pas un bug.",
  "L'API externe était indisponible.",
  "Je pense que c'est un souci de localStorage.",
  'Tout dépend du timing.',
  'Il faut vider le cache du navigateur.',
  'Il manque un point-virgule quelque part.',
  'C’est une classique condition de course.',
  'Le serveur n’était pas prêt.',
  'Ça marche en production, je ne sais pas pourquoi.',
  'Le client n’a pas donné assez de détails.',
  "C'est un problème en aval.",
  'Je l’avais corrigé localement, mais j’ai oublié de commit.',
  'C’est une incompatibilité de navigateur.',
  'La base de données était lente ce jour-là.',
];
const DEFAULT_DAILY_ALGO_PROBLEMS = [
  {
    title: 'Inverser une chaîne',
    description: 'Écris une fonction qui inverse une chaîne de caractères sans utiliser les méthodes built-in.',
    solution: 'Utilise une boucle ou la récursion pour parcourir la chaîne à l\'envers.',
    difficulty: 'facile',
    functionName: 'reverseString',
    functionArgs: [{ name: 'input', type: 'string' }],
    allowedLanguages: ['javascript', 'typescript', 'python'],
    unitTests: [
      { name: 'mot simple', args: ['hello'], expected: 'olleh' },
      { name: 'palindrome', args: ['racecar'], expected: 'racecar' },
      { name: 'chaine vide', args: [''], expected: '' },
    ],
  },
  {
    title: 'Fibonacci',
    description: 'Implémente une fonction qui retourne le Nième nombre de Fibonacci de manière efficace.',
    solution: 'Utilise la programmation dynamique ou la récursion avec mémoïsation pour éviter les recalculs.',
    difficulty: 'moyen',
    functionName: 'fibonacci',
    functionArgs: [{ name: 'n', type: 'number' }],
    allowedLanguages: ['javascript', 'typescript', 'python'],
    unitTests: [
      { name: 'fibo 0', args: [0], expected: 0 },
      { name: 'fibo 1', args: [1], expected: 1 },
      { name: 'fibo 7', args: [7], expected: 13 },
      { name: 'fibo 10', args: [10], expected: 55 },
    ],
  },
  {
    title: 'Vérifier un palindrome',
    description: 'Écris une fonction pour vérifier si une chaîne est un palindrome (ignore les espaces et la casse).',
    solution: 'Compare la chaîne avec sa version inversée après normalisation.',
    difficulty: 'facile',
    functionName: 'isPalindrome',
    functionArgs: [{ name: 'input', type: 'string' }],
    allowedLanguages: ['javascript', 'typescript', 'python'],
    unitTests: [
      { name: 'palindrome simple', args: ['kayak'], expected: true },
      { name: 'palindrome avec espaces', args: ['Never odd or even'], expected: true },
      { name: 'pas palindrome', args: ['hello'], expected: false },
    ],
  },
  {
    title: 'Deux sommes',
    description: 'Trouve deux nombres dans un tableau qui s\'additionnent pour égaler une cible.',
    solution: 'Utilise une Map/Set pour stocker les nombres vus et trouve le complément en O(n).',
    difficulty: 'moyen',
    functionName: 'twoSum',
    functionArgs: [
      { name: 'nums', type: 'number[]' },
      { name: 'target', type: 'number' },
    ],
    allowedLanguages: ['javascript', 'typescript', 'python'],
    unitTests: [
      { name: 'cas classique', args: [[2, 7, 11, 15], 9], expected: [0, 1] },
      { name: 'valeurs dupliquees', args: [[3, 3], 6], expected: [0, 1] },
      { name: 'autre tableau', args: [[3, 2, 4], 6], expected: [1, 2] },
    ],
  },
  {
    title: 'Parenthèses valides',
    description: 'Vérifie si une chaîne de parenthèses/crochets/accolades est correctement équilibrée.',
    solution: 'Utilise une pile (stack) pour tracker les ouvertures et vérifier les fermetures.',
    difficulty: 'moyen',
    functionName: 'isValidParentheses',
    functionArgs: [{ name: 'input', type: 'string' }],
    allowedLanguages: ['javascript', 'typescript', 'python'],
    unitTests: [
      { name: 'valide simple', args: ['()[]{}'], expected: true },
      { name: 'ordre invalide', args: ['([)]'], expected: false },
      { name: 'imbrique valide', args: ['{[()]}'], expected: true },
    ],
  },
  {
    title: 'Nombre premier',
    description: 'Crée une fonction pour vérifier si un nombre donné est un nombre premier.',
    solution: 'Vérifie les diviseurs jusqu\'à la racine carrée du nombre.',
    difficulty: 'facile',
    functionName: 'isPrime',
    functionArgs: [{ name: 'n', type: 'number' }],
    allowedLanguages: ['javascript', 'typescript', 'python'],
    unitTests: [
      { name: '2 est premier', args: [2], expected: true },
      { name: '9 n est pas premier', args: [9], expected: false },
      { name: '17 est premier', args: [17], expected: true },
      { name: '1 n est pas premier', args: [1], expected: false },
    ],
  },
  {
    title: 'Maximum de tableau',
    description: 'Trouve l\'élément maximum dans un tableau sans utiliser Math.max().',
    solution: 'Parcours le tableau en gardant trace du maximum rencontré.',
    difficulty: 'facile',
    functionName: 'maxInArray',
    functionArgs: [{ name: 'values', type: 'number[]' }],
    allowedLanguages: ['javascript', 'typescript', 'python'],
    unitTests: [
      { name: 'valeurs positives', args: [[1, 4, 2, 9, 3]], expected: 9 },
      { name: 'valeurs negatives', args: [[-5, -1, -9]], expected: -1 },
      { name: 'singleton', args: [[42]], expected: 42 },
    ],
  },
  {
    title: 'Fusionner deux tableaux triés',
    description: 'Fusionne deux tableaux triés en un seul tableau trié en O(n + m).',
    solution: 'Utilise deux pointeurs pour comparer et ajouter le plus petit élément en priorité.',
    difficulty: 'moyen',
    functionName: 'mergeSortedArrays',
    functionArgs: [
      { name: 'left', type: 'number[]' },
      { name: 'right', type: 'number[]' },
    ],
    allowedLanguages: ['javascript', 'typescript', 'python'],
    unitTests: [
      { name: 'fusion classique', args: [[1, 3, 5], [2, 4, 6]], expected: [1, 2, 3, 4, 5, 6] },
      { name: 'tableau vide gauche', args: [[], [1, 2]], expected: [1, 2] },
      { name: 'tableau vide droite', args: [[1, 2], []], expected: [1, 2] },
    ],
  },
  {
    title: 'Anagrammes',
    description: 'Détermine si deux chaînes sont des anagrammes (même lettres, ordre différent).',
    solution: 'Compare les fréquences de caractères ou les chaînes triées.',
    difficulty: 'facile',
    functionName: 'areAnagrams',
    functionArgs: [
      { name: 'a', type: 'string' },
      { name: 'b', type: 'string' },
    ],
    allowedLanguages: ['javascript', 'typescript', 'python'],
    unitTests: [
      { name: 'anagramme simple', args: ['chien', 'niche'], expected: true },
      { name: 'pas anagramme', args: ['chat', 'chien'], expected: false },
      { name: 'casse et espaces', args: ['Dormitory', 'Dirty room'], expected: true },
    ],
  },
  {
    title: 'Sous-tableau avec somme max',
    description: 'Trouve la somme maximale d\'un sous-tableau contigu (Kadane\'s algorithm).',
    solution: 'Utilise la programmation dynamique pour tracker la somme locale et globale.',
    difficulty: 'difficile',
    functionName: 'maxSubarraySum',
    functionArgs: [{ name: 'values', type: 'number[]' }],
    allowedLanguages: ['javascript', 'typescript', 'python'],
    unitTests: [
      { name: 'kadane classique', args: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6 },
      { name: 'tout negatif', args: [[-8, -3, -6, -2, -5, -4]], expected: -2 },
      { name: 'tout positif', args: [[1, 2, 3, 4]], expected: 10 },
    ],
  },
];

const DEFAULT_CODE_POLICE_RULES = [
  { key: 'signal.js.function', category: 'SIGNAL', matchType: 'EXACT', language: 'javascript', pattern: 'function', label: 'Fonction JavaScript', feedback: 'Repère une définition de fonction JavaScript.' , severity: 'INFO' },
  { key: 'signal.js.const', category: 'SIGNAL', matchType: 'EXACT', language: 'javascript', pattern: 'const', label: 'Constante JavaScript', feedback: 'Repère une constante ou une variable en JavaScript.', severity: 'INFO' },
  { key: 'signal.js.let', category: 'SIGNAL', matchType: 'EXACT', language: 'javascript', pattern: 'let', label: 'Variable JavaScript', feedback: 'Repère une variable mutable en JavaScript.', severity: 'INFO' },
  { key: 'signal.js.var', category: 'SIGNAL', matchType: 'EXACT', language: 'javascript', pattern: 'var', label: 'Variable historique JavaScript', feedback: 'Repère une déclaration historique en JavaScript.', severity: 'INFO' },
  { key: 'signal.js.async', category: 'SIGNAL', matchType: 'EXACT', language: 'javascript', pattern: 'async', label: 'Asynchrone JavaScript', feedback: 'Repère un bloc ou une fonction asynchrone.', severity: 'INFO' },
  { key: 'signal.js.await', category: 'SIGNAL', matchType: 'EXACT', language: 'javascript', pattern: 'await', label: 'Attente JavaScript', feedback: 'Repère un appel en attente.', severity: 'INFO' },
  { key: 'signal.js.class', category: 'SIGNAL', matchType: 'EXACT', language: 'javascript', pattern: 'class', label: 'Classe JavaScript', feedback: 'Repère une classe.', severity: 'INFO' },
  { key: 'signal.js.import', category: 'SIGNAL', matchType: 'EXACT', language: 'javascript', pattern: 'import', label: 'Import JavaScript', feedback: 'Repère un import ES module.', severity: 'INFO' },
  { key: 'signal.js.export', category: 'SIGNAL', matchType: 'EXACT', language: 'javascript', pattern: 'export', label: 'Export JavaScript', feedback: 'Repère un export ES module.', severity: 'INFO' },
  { key: 'signal.js.console.log', category: 'SIGNAL', matchType: 'EXACT', language: 'javascript', pattern: 'console.log', label: 'Console JavaScript', feedback: 'Repère une sortie console.', severity: 'INFO' },
  { key: 'signal.python.def', category: 'SIGNAL', matchType: 'REGEX', language: 'python', pattern: '\\bdef\\s+[A-Za-z_][\\w]*\\s*\\(', label: 'Fonction Python', feedback: 'Repère une fonction Python.', severity: 'INFO' },
  { key: 'signal.python.import', category: 'SIGNAL', matchType: 'REGEX', language: 'python', pattern: '\\bimport\\s+[A-Za-z_][\\w.]*\\b', label: 'Import Python', feedback: 'Repère un import Python.', severity: 'INFO' },
  { key: 'signal.python.print', category: 'SIGNAL', matchType: 'REGEX', language: 'python', pattern: '\\bprint\\s*\\(', label: 'Print Python', feedback: 'Repère une impression Python.', severity: 'INFO' },
  { key: 'signal.sql.select', category: 'SIGNAL', matchType: 'EXACT', language: 'sql', pattern: 'SELECT', label: 'SELECT SQL', feedback: 'Repère une requête SQL.', severity: 'INFO' },
  { key: 'signal.sql.from', category: 'SIGNAL', matchType: 'EXACT', language: 'sql', pattern: 'FROM', label: 'FROM SQL', feedback: 'Repère une clause SQL.', severity: 'INFO' },
  { key: 'signal.sql.where', category: 'SIGNAL', matchType: 'EXACT', language: 'sql', pattern: 'WHERE', label: 'WHERE SQL', feedback: 'Repère un filtre SQL.', severity: 'INFO' },
  { key: 'signal.shell.sudo', category: 'SIGNAL', matchType: 'EXACT', language: 'shell', pattern: 'sudo', label: 'Commande shell', feedback: 'Repère une commande shell sensible.', severity: 'INFO' },
  { key: 'signal.shell.git', category: 'SIGNAL', matchType: 'EXACT', language: 'shell', pattern: 'git', label: 'Commande git', feedback: 'Repère une commande Git.', severity: 'INFO' },
  { key: 'signal.java.public-class', category: 'SIGNAL', matchType: 'REGEX', language: 'java', pattern: '\\bpublic\\s+(?:class|interface|enum)\\b', label: 'Classe Java', feedback: 'Repère une structure Java.', severity: 'INFO' },
  { key: 'signal.java.system-out', category: 'SIGNAL', matchType: 'EXACT', language: 'java', pattern: 'System.out.println', label: 'Console Java', feedback: 'Repère une sortie console Java.', severity: 'INFO' },
  { key: 'signal.cpp.include', category: 'SIGNAL', matchType: 'REGEX', language: 'cpp', pattern: '\\b#include\\b', label: 'Include C++', feedback: 'Repère un include C++.', severity: 'INFO' },
  { key: 'signal.html.tag', category: 'SIGNAL', matchType: 'REGEX', language: 'html', pattern: '<\\/?[a-z][\\w-]*(?:\\s+[^<>]*)?>', label: 'Balise HTML', feedback: 'Repère une balise HTML.', severity: 'INFO' },
  { key: 'signal.syntax.block', category: 'SIGNAL', matchType: 'REGEX', language: 'generic', pattern: '[{}\\[\\]();=>]', label: 'Syntaxe de bloc', feedback: 'Repère une syntaxe de bloc typique du code.', severity: 'INFO' },
  { key: 'signal.control.flow', category: 'SIGNAL', matchType: 'REGEX', language: 'generic', pattern: '(?:^|\\n)\\s*(?:if|for|while|switch|try|catch|else)\\s*\\(', label: 'Contrôle de flux', feedback: 'Repère une structure de contrôle.', severity: 'INFO' },
  { key: 'signal.indentation.block', category: 'SIGNAL', matchType: 'REGEX', language: 'generic', pattern: '(?:^|\\n)\\s{2,}\\S', label: 'Indentation de bloc', feedback: 'Repère une indentation typique de code.', severity: 'INFO' },
  { key: 'signal.shell.pipeline', category: 'SIGNAL', matchType: 'REGEX', language: 'shell', pattern: '\\b(?:curl|wget|npm|pip|docker|kubectl|rm|chmod|cat|echo|grep|sed|awk)\\b', label: 'Commande shell', feedback: 'Repère une commande shell courante.', severity: 'INFO' },
  { key: 'danger.eval', category: 'DANGER', matchType: 'REGEX', language: 'javascript', pattern: '\\b(?:eval|Function)\\s*\\(', label: 'Évaluation dynamique', feedback: 'Évite l\'évaluation dynamique de code quand ce n\'est pas strictement nécessaire.', severity: 'DANGER' },
  { key: 'danger.timer', category: 'DANGER', matchType: 'REGEX', language: 'javascript', pattern: '\\b(?:setTimeout|setInterval)\\s*\\(', label: 'Timer dynamique', feedback: 'Vérifie que le délai est borné et que la donnée exécutée n\'est pas injectée par un utilisateur.', severity: 'WARNING' },
  { key: 'danger.child-process', category: 'DANGER', matchType: 'REGEX', language: 'generic', pattern: '\\b(?:child_process\\.(?:exec|execSync|spawn|spawnSync)|os\\.system|subprocess\\.(?:run|Popen|call|check_output)|Runtime\\.getRuntime\\(\\)\\.exec|ProcessBuilder)\\b', label: 'Appel système', feedback: 'Les appels système directs doivent être verrouillés et validés avant exécution.', severity: 'DANGER' },
  { key: 'danger.rm-rf', category: 'DANGER', matchType: 'REGEX', language: 'shell', pattern: '(?:rm\\s+-rf\\s+\\/|del\\s+\\/f\\s+\\/q|Remove-Item\\s+-Recurse\\s+-Force|format\\s+[a-z]:|mkfs\\.|dd\\s+if=\\/dev\\/zero)', label: 'Destruction de fichiers', feedback: 'Cette commande peut supprimer ou écraser des données critiques.', severity: 'DANGER' },
  { key: 'danger.curl-bash', category: 'DANGER', matchType: 'REGEX', language: 'shell', pattern: '(?:curl|wget).*(?:\\||;).*(?:sh|bash|powershell|pwsh)', label: 'Téléchargement puis exécution', feedback: 'Télécharger puis exécuter une commande directement est très risqué.', severity: 'DANGER' },
  { key: 'danger.payload', category: 'DANGER', matchType: 'REGEX', language: 'generic', pattern: '(?:base64\\s+-d|atob\\(|btoa\\(|Buffer\\.from\\().*(?:\\||;).*(?:sh|bash|python|node|pwsh)', label: 'Charge utile masquée', feedback: 'Le décodage suivi d\'une exécution peut masquer un payload malveillant.', severity: 'DANGER' },
  { key: 'danger.fork-bomb', category: 'DANGER', matchType: 'REGEX', language: 'shell', pattern: ':\\(\\)\\s*\\{\\s*:\\|:&\\s*\\};:', label: 'Fork bomb', feedback: 'Cette charge utile peut saturer la machine en quelques secondes.', severity: 'DANGER' },
  { key: 'language.javascript', category: 'LANGUAGE_FEEDBACK', matchType: 'EXACT', language: 'javascript', pattern: 'javascript', label: 'Conseil JavaScript', feedback: 'JS/TS : évite eval, borne les boucles et préfère des gardes explicites avant toute récursion.', severity: 'INFO' },
  { key: 'language.python', category: 'LANGUAGE_FEEDBACK', matchType: 'EXACT', language: 'python', pattern: 'python', label: 'Conseil Python', feedback: 'Python : ajoute un cas de base aux fonctions récursives et évite les appels système non filtrés.', severity: 'INFO' },
  { key: 'language.sql', category: 'LANGUAGE_FEEDBACK', matchType: 'EXACT', language: 'sql', pattern: 'sql', label: 'Conseil SQL', feedback: 'SQL : privilégie les requêtes paramétrées et évite la concaténation directe de chaînes.', severity: 'INFO' },
  { key: 'language.shell', category: 'LANGUAGE_FEEDBACK', matchType: 'EXACT', language: 'shell', pattern: 'shell', label: 'Conseil Shell', feedback: 'Shell : vérifie chaque commande avant exécution, surtout si elle vient d\'une entrée utilisateur.', severity: 'INFO' },
  { key: 'language.html', category: 'LANGUAGE_FEEDBACK', matchType: 'EXACT', language: 'html', pattern: 'html', label: 'Conseil HTML', feedback: 'HTML/CSS : si du script est injecté, vérifie l\'assainissement des données avant rendu.', severity: 'INFO' },
  { key: 'language.java', category: 'LANGUAGE_FEEDBACK', matchType: 'EXACT', language: 'java', pattern: 'java', label: 'Conseil Java', feedback: 'Java : surveille les boucles sans sortie et les exécutions de commandes externes.', severity: 'INFO' },
  { key: 'language.cpp', category: 'LANGUAGE_FEEDBACK', matchType: 'EXACT', language: 'cpp', pattern: 'cpp', label: 'Conseil C++', feedback: 'C++ : surveille les accès mémoire, les boucles infinies et les appels système.', severity: 'INFO' },
  { key: 'language.generic', category: 'LANGUAGE_FEEDBACK', matchType: 'EXACT', language: 'generic', pattern: 'generic', label: 'Conseil générique', feedback: 'Bonne pratique : ajoute un cas de sortie clair, borne les itérations et valide toutes les entrées.', severity: 'INFO' },
] as const;

const DEFAULT_BANNED_WORDS = [
  // RACISM
  { word: 'nègre', category: 'racism' },
  { word: 'négresse', category: 'racism' },
  { word: 'nigger', category: 'racism' },
  { word: 'nigga', category: 'racism' },
  { word: 'bamboula', category: 'racism' },
  { word: 'bougnoule', category: 'racism' },
  { word: 'bicot', category: 'racism' },
  { word: 'chinetoc', category: 'racism' },
  { word: 'chinetoque', category: 'racism' },
  { word: 'macaque', category: 'racism' },
  { word: 'chink', category: 'racism' },
  { word: 'gook', category: 'racism' },
  { word: 'coon', category: 'racism' },

  // THREAT
  { word: 'tuer', category: 'threat' },
  { word: 'assassiner', category: 'threat' },
  { word: 'égorger', category: 'threat' },
  { word: 'bombe', category: 'threat' },
  { word: 'terroriste', category: 'threat' },
  { word: 'suicide', category: 'threat' },
  { word: 'pendre', category: 'threat' },
  { word: 'décapiter', category: 'threat' },
  { word: 'fusiller', category: 'threat' },
  { word: 'massacrer', category: 'threat' },
  { word: 'kill', category: 'threat' },
  { word: 'murder', category: 'threat' },
  { word: 'bomb', category: 'threat' },
  { word: 'terrorist', category: 'threat' },
  { word: 'explosif', category: 'threat' },
  { word: 'kamikaze', category: 'threat' },
  { word: 'k4mikaze', category: 'threat' },
  { word: 'kamikaz', category: 'threat' },
  { word: 'k4mikaz', category: 'threat' },
  { word: 'kamikase', category: 'threat' },
  { word: 'k4mikase', category: 'threat' },

  // SEXUAL
  { word: 'bite', category: 'sexual' },
  { word: 'chatte', category: 'sexual' },
  { word: 'salope', category: 'sexual' },
  { word: 'pute', category: 'sexual' },
  { word: 'pouffiasse', category: 'sexual' },
  { word: 'couille', category: 'sexual' },
  { word: 'couilles', category: 'sexual' },
  { word: 'pénis', category: 'sexual' },
  { word: 'penis', category: 'sexual' },
  { word: 'vagin', category: 'sexual' },
  { word: 'clitoris', category: 'sexual' },
  { word: 'sperme', category: 'sexual' },
  { word: 'branler', category: 'sexual' },
  { word: 'branlette', category: 'sexual' },
  { word: 'fellation', category: 'sexual' },
  { word: 'cunnilingus', category: 'sexual' },
  { word: 'sodomie', category: 'sexual' },
  { word: 'porno', category: 'sexual' },
  { word: 'porn', category: 'sexual' },
  { word: 'nude', category: 'sexual' },
  { word: 'nudes', category: 'sexual' },
  { word: 'hentai', category: 'sexual' },
  { word: 'pédophile', category: 'sexual' },
  { word: 'pedophile', category: 'sexual' },
  { word: 'zoophile', category: 'sexual' },
  { word: 'inceste', category: 'sexual' },
  { word: 'dick', category: 'sexual' },
  { word: 'pussy', category: 'sexual' },
  { word: 'whore', category: 'sexual' },
  { word: 'slut', category: 'sexual' },
  { word: 'cock', category: 'sexual' },
  { word: 'cunt', category: 'sexual' },
  { word: 'vagina', category: 'sexual' },
  { word: 'sperm', category: 'sexual' },
  { word: 'masturbate', category: 'sexual' },
  { word: 'blowjob', category: 'sexual' },
  { word: 'goon', category: 'sexual' },
  { word: 'gooner', category: 'sexual' },
  { word: 'gooners', category: 'sexual' },
  { word: 'gooning', category: 'sexual' },
  { word: 'goonette', category: 'sexual' },

  // LGBTPHOBIA
  { word: 'pédé', category: 'lgbtphobia' },
  { word: 'pedé', category: 'lgbtphobia' },
  { word: 'tarlouze', category: 'lgbtphobia' },
  { word: 'tapette', category: 'lgbtphobia' },
  { word: 'goudou', category: 'lgbtphobia' },
  { word: 'gouine', category: 'lgbtphobia' },
  { word: 'faggot', category: 'lgbtphobia' },
  { word: 'tranny', category: 'lgbtphobia' },
  { word: 'homophobe', category: 'lgbtphobia' },
  { word: 'transphobe', category: 'lgbtphobia' },
  { word: 'fag', category: 'lgbtphobia' },
  { word: 'dyke', category: 'lgbtphobia' },

  // HATE
  { word: 'nazi', category: 'hate' },
  { word: 'hitler', category: 'hate' },
  { word: 'swastika', category: 'hate' },
  { word: 'fasciste', category: 'hate' },
  { word: 'fachiste', category: 'hate' },
  { word: 'antisémite', category: 'hate' },
  { word: 'antisemitic', category: 'hate' },
  { word: 'croix gammée', category: 'hate' },
  { word: 'ku klux klan', category: 'hate' },
  { word: 'kkk', category: 'hate' },
  { word: 'suprématiste', category: 'hate' },
  { word: 'supremacist', category: 'hate' },

  { word: 'supremacist', category: 'hate' },

  // INSULT
  { word: 'con', category: 'insult' },
  { word: 'connard', category: 'insult' },
  { word: 'connasse', category: 'insult' },
  { word: 'salopard', category: 'insult' },
  { word: 'fdp', category: 'insult' },
  { word: 'fils de pute', category: 'insult' },
  { word: 'merde', category: 'insult' },
  { word: 'enculé', category: 'insult' },
  { word: 'encule', category: 'insult' },
  { word: 'abruti', category: 'insult' },
  { word: 'débile', category: 'insult' },
  { word: 'debile', category: 'insult' },
  { word: 'mongol', category: 'insult' },
  { word: 'tocard', category: 'insult' },
  { word: 'crevard', category: 'insult' },
  { word: 'bâtard', category: 'insult' },
  { word: 'batard', category: 'insult' },
  { word: 'gogol', category: 'insult' },
  { word: 'bouffon', category: 'insult' },
  { word: 'asshole', category: 'insult' },
  { word: 'bastard', category: 'insult' },
  { word: 'motherfucker', category: 'insult' },
  { word: 'idiot', category: 'insult' },
  { word: 'retard', category: 'insult' },
  { word: 'dumbass', category: 'insult' },
  { word: 'jerk', category: 'insult' },
  { word: 'piece of shit', category: 'insult' },

  // --- BIG EXPANSION (Français & Anglais, Leetspeak formulations) ---
  // --- RACISM & XENOPHOBIA ---
  { word: 'bougnoul', category: 'racism' },
  { word: 'bougnoules', category: 'racism' },
  { word: 'b0ugnoule', category: 'racism' },
  { word: 'b0ugn0ule', category: 'racism' },
  { word: 'negre', category: 'racism' },
  { word: 'negresse', category: 'racism' },
  { word: 'n1gger', category: 'racism' },
  { word: 'n1gga', category: 'racism' },
  { word: 'niggah', category: 'racism' },
  { word: 'niggas', category: 'racism' },
  { word: 'niggers', category: 'racism' },
  { word: 'ni99er', category: 'racism' },
  { word: 'ni99a', category: 'racism' },
  { word: 'n_i_g_g_e_r', category: 'racism' },
  { word: 'n_i_g_g_a', category: 'racism' },
  { word: 'macaques', category: 'racism' },
  { word: 'macak', category: 'racism' },
  { word: 'macaq', category: 'racism' },
  { word: 'chinetoks', category: 'racism' },
  { word: 'chinetoq', category: 'racism' },
  { word: 'chine-toc', category: 'racism' },
  { word: 'bamboulas', category: 'racism' },
  { word: 'bougni', category: 'racism' },
  { word: 'bicots', category: 'racism' },
  { word: 'chinks', category: 'racism' },
  { word: 'ch1nk', category: 'racism' },
  { word: 'gooks', category: 'racism' },
  { word: 'g00k', category: 'racism' },
  { word: 'coons', category: 'racism' },
  { word: 'c00n', category: 'racism' },
  { word: 'c00ns', category: 'racism' },
  { word: 'kike', category: 'racism' },
  { word: 'kyke', category: 'racism' },
  { word: 'kikes', category: 'racism' },
  { word: 'spic', category: 'racism' },
  { word: 'spick', category: 'racism' },
  { word: 'spics', category: 'racism' },
  { word: 'wog', category: 'racism' },
  { word: 'wogs', category: 'racism' },
  { word: 'wetback', category: 'racism' },
  { word: 'paki', category: 'racism' },
  { word: 'pakis', category: 'racism' },
  { word: 'p4ki', category: 'racism' },
  { word: 'yid', category: 'racism' },
  { word: 'yids', category: 'racism' },
  { word: 'raghead', category: 'racism' },
  { word: 'towelhead', category: 'racism' },
  { word: 'cholo', category: 'racism' },
  { word: 'gringo', category: 'racism' },
  { word: 'gringos', category: 'racism' },
  { word: 'goy', category: 'racism' },
  { word: 'goyim', category: 'racism' },
  { word: 'goyms', category: 'racism' },
  { word: 'negro', category: 'racism' },
  { word: 'negros', category: 'racism' },
  { word: 'negroes', category: 'racism' },
  { word: 'négro', category: 'racism' },
  { word: 'négros', category: 'racism' },
  { word: 'n0irade', category: 'racism' },
  { word: 'noirade', category: 'racism' },
  { word: 'noirades', category: 'racism' },
  { word: 'savage', category: 'racism' },
  { word: 'savages', category: 'racism' },
  { word: 'sauvageon', category: 'racism' },
  { word: 'sauvageons', category: 'racism' },
  { word: 'kaffir', category: 'racism' },
  { word: 'kaffirs', category: 'racism' },
  { word: 'jungle bunny', category: 'racism' },
  { word: 'porc-noir', category: 'racism' },
  { word: 'sale arabe', category: 'racism' },
  { word: 'sale noir', category: 'racism' },
  { word: 'sale blanc', category: 'racism' },
  { word: 'sale juif', category: 'racism' },
  { word: 'sale chinois', category: 'racism' },
  { word: 'dirty jew', category: 'racism' },
  { word: 'dirty arab', category: 'racism' },
  { word: 'dirty black', category: 'racism' },
  { word: 'dirty white', category: 'racism' },

  // --- THREAT & VIOLENCE ---
  { word: 'tueras', category: 'threat' },
  { word: 'tuerai', category: 'threat' },
  { word: 'tuons', category: 'threat' },
  { word: 'tuez', category: 'threat' },
  { word: 'tueront', category: 'threat' },
  { word: 'assassins', category: 'threat' },
  { word: 'assassine', category: 'threat' },
  { word: 'assassinat', category: 'threat' },
  { word: 'assassinats', category: 'threat' },
  { word: 'égorgements', category: 'threat' },
  { word: 'égorge', category: 'threat' },
  { word: 'egorger', category: 'threat' },
  { word: 'egorge', category: 'threat' },
  { word: 'decapiter', category: 'threat' },
  { word: 'décapite', category: 'threat' },
  { word: 'decapite', category: 'threat' },
  { word: 'decapitation', category: 'threat' },
  { word: 'décapitation', category: 'threat' },
  { word: 'bombes', category: 'threat' },
  { word: 'bombardement', category: 'threat' },
  { word: 'b0mbe', category: 'threat' },
  { word: 'b0mbes', category: 'threat' },
  { word: 'explosifs', category: 'threat' },
  { word: 'explosion', category: 'threat' },
  { word: 'c4', category: 'threat' },
  { word: 'semtex', category: 'threat' },
  { word: 'dynamite', category: 'threat' },
  { word: 'attentat', category: 'threat' },
  { word: 'attentats', category: 'threat' },
  { word: 'terrorisme', category: 'threat' },
  { word: 'terroristes', category: 'threat' },
  { word: 'terr0riste', category: 'threat' },
  { word: 'suicides', category: 'threat' },
  { word: 'suicidaire', category: 'threat' },
  { word: 'suicider', category: 'threat' },
  { word: 'pendaison', category: 'threat' },
  { word: 'pendus', category: 'threat' },
  { word: 'pendu', category: 'threat' },
  { word: 'pende', category: 'threat' },
  { word: 'fusillade', category: 'threat' },
  { word: 'fusillades', category: 'threat' },
  { word: 'fusil', category: 'threat' },
  { word: 'massacres', category: 'threat' },
  { word: 'massacrant', category: 'threat' },
  { word: 'assaut', category: 'threat' },
  { word: 'égorgement', category: 'threat' },
  { word: 'throatcut', category: 'threat' },
  { word: 'killing', category: 'threat' },
  { word: 'kills', category: 'threat' },
  { word: 'killer', category: 'threat' },
  { word: 'killers', category: 'threat' },
  { word: 'k1ll', category: 'threat' },
  { word: 'k1ller', category: 'threat' },
  { word: 'k1lling', category: 'threat' },
  { word: 'murders', category: 'threat' },
  { word: 'murderer', category: 'threat' },
  { word: 'murderers', category: 'threat' },
  { word: 'murd3r', category: 'threat' },
  { word: 'bombs', category: 'threat' },
  { word: 'bomber', category: 'threat' },
  { word: 'bombers', category: 'threat' },
  { word: 'bombing', category: 'threat' },
  { word: 'b0mb', category: 'threat' },
  { word: 'b0mbs', category: 'threat' },
  { word: 'terrorists', category: 'threat' },
  { word: 'terrorism', category: 'threat' },
  { word: 'terr0rist', category: 'threat' },
  { word: 'genocide', category: 'threat' },
  { word: 'génocide', category: 'threat' },
  { word: 'genocides', category: 'threat' },
  { word: 'génocides', category: 'threat' },
  { word: 'poison', category: 'threat' },
  { word: 'poisoning', category: 'threat' },
  { word: 'poisoned', category: 'threat' },
  { word: 'empoisonner', category: 'threat' },
  { word: 'fusille', category: 'threat' },
  { word: 'kalach', category: 'threat' },
  { word: 'kalachnikov', category: 'threat' },
  { word: 'ak47', category: 'threat' },
  { word: 'ar15', category: 'threat' },
  { word: 'fusil-mitrailleur', category: 'threat' },
  { word: 'guerre', category: 'threat' },
  { word: 'djihad', category: 'threat' },
  { word: 'jihad', category: 'threat' },
  { word: 'djihadiste', category: 'threat' },
  { word: 'jihadist', category: 'threat' },
  { word: 'djihadistes', category: 'threat' },
  { word: 'jihadists', category: 'threat' },
  { word: 'calife', category: 'threat' },
  { word: 'califat', category: 'threat' },
  { word: 'caliphate', category: 'threat' },
  { word: 'daesh', category: 'threat' },
  { word: 'isis', category: 'threat' },
  { word: 'al-qaida', category: 'threat' },
  { word: 'alqaida', category: 'threat' },
  { word: 'al-qaïda', category: 'threat' },
  { word: 'taliban', category: 'threat' },
  { word: 'talibans', category: 'threat' },
  { word: 'boko haram', category: 'threat' },
  { word: 'bokoharam', category: 'threat' },
  { word: 'suicide bomb', category: 'threat' },
  { word: 'suicide bomber', category: 'threat' },
  { word: 'school shooting', category: 'threat' },
  { word: 'school shooter', category: 'threat' },
  { word: 'columbine', category: 'threat' },
  { word: 'hate speech', category: 'threat' },
  { word: 'threaten', category: 'threat' },
  { word: 'threatening', category: 'threat' },
  { word: 'threats', category: 'threat' },
  { word: 'menace', category: 'threat' },
  { word: 'menaces', category: 'threat' },
  { word: 'menacer', category: 'threat' },
  { word: 'm4nikaze', category: 'threat' },
  { word: 'kamikazes', category: 'threat' },
  { word: 'k4mikazes', category: 'threat' },
  { word: 'kamikases', category: 'threat' },
  { word: 'k4mikases', category: 'threat' },
  { word: 'kamikazs', category: 'threat' },
  { word: 'k4mikazs', category: 'threat' },

  // --- SEXUAL & PORNOGRAPHIC ---
  { word: 'bites', category: 'sexual' },
  { word: 'b1te', category: 'sexual' },
  { word: 'b1tes', category: 'sexual' },
  { word: 'chattes', category: 'sexual' },
  { word: 'shatte', category: 'sexual' },
  { word: 'shattes', category: 'sexual' },
  { word: 'salopes', category: 'sexual' },
  { word: 's4lope', category: 'sexual' },
  { word: 's4lopes', category: 'sexual' },
  { word: 'putes', category: 'sexual' },
  { word: 'p_u_t_e', category: 'sexual' },
  { word: 'p1te', category: 'sexual' },
  { word: 'p1tes', category: 'sexual' },
  { word: 'putain', category: 'sexual' },
  { word: 'putains', category: 'sexual' },
  { word: 'pouffiasses', category: 'sexual' },
  { word: 'couillere', category: 'sexual' },
  { word: 'c0uille', category: 'sexual' },
  { word: 'c0uilles', category: 'sexual' },
  { word: 'péniss', category: 'sexual' },
  { word: 'peniss', category: 'sexual' },
  { word: 'p3nis', category: 'sexual' },
  { word: 'vagins', category: 'sexual' },
  { word: 'v4gin', category: 'sexual' },
  { word: 'v4gins', category: 'sexual' },
  { word: 'clito', category: 'sexual' },
  { word: 'clitos', category: 'sexual' },
  { word: 'clit0ris', category: 'sexual' },
  { word: 'spermes', category: 'sexual' },
  { word: 'cum', category: 'sexual' },
  { word: 'cumshot', category: 'sexual' },
  { word: 'cumshots', category: 'sexual' },
  { word: 'cuming', category: 'sexual' },
  { word: 'orgasme', category: 'sexual' },
  { word: 'orgasmes', category: 'sexual' },
  { word: 'orgasm', category: 'sexual' },
  { word: 'orgasms', category: 'sexual' },
  { word: 'ejaculation', category: 'sexual' },
  { word: 'éjaculation', category: 'sexual' },
  { word: 'ejaculer', category: 'sexual' },
  { word: 'éjaculer', category: 'sexual' },
  { word: 'masturbation', category: 'sexual' },
  { word: 'masturber', category: 'sexual' },
  { word: 'masturbes', category: 'sexual' },
  { word: 'branlette espagnole', category: 'sexual' },
  { word: 'fellations', category: 'sexual' },
  { word: 'cunnilinguss', category: 'sexual' },
  { word: 'deepthroat', category: 'sexual' },
  { word: 'sodomies', category: 'sexual' },
  { word: 'sodomiser', category: 'sexual' },
  { word: 'sodomise', category: 'sexual' },
  { word: 'sodomized', category: 'sexual' },
  { word: 'sodomize', category: 'sexual' },
  { word: 'enculade', category: 'sexual' },
  { word: 'pornos', category: 'sexual' },
  { word: 'pornographie', category: 'sexual' },
  { word: 'pornography', category: 'sexual' },
  { word: 'p0rno', category: 'sexual' },
  { word: 'p0rn', category: 'sexual' },
  { word: 'p0rnography', category: 'sexual' },
  { word: 'hentais', category: 'sexual' },
  { word: 'h3ntai', category: 'sexual' },
  { word: 'ecchi', category: 'sexual' },
  { word: 'nsfw', category: 'sexual' },
  { word: 'pedophiles', category: 'sexual' },
  { word: 'pédophiles', category: 'sexual' },
  { word: 'pédophilie', category: 'sexual' },
  { word: 'pedophilia', category: 'sexual' },
  { word: 'ped0phile', category: 'sexual' },
  { word: 'zoophiles', category: 'sexual' },
  { word: 'zoophilia', category: 'sexual' },
  { word: 'bestiality', category: 'sexual' },
  { word: 'incestes', category: 'sexual' },
  { word: 'incestuous', category: 'sexual' },
  { word: 'incest', category: 'sexual' },
  { word: 'dicks', category: 'sexual' },
  { word: 'd1ck', category: 'sexual' },
  { word: 'd1cks', category: 'sexual' },
  { word: 'pussies', category: 'sexual' },
  { word: 'pussys', category: 'sexual' },
  { word: 'puss1e', category: 'sexual' },
  { word: 'whores', category: 'sexual' },
  { word: 'wh0re', category: 'sexual' },
  { word: 'wh0res', category: 'sexual' },
  { word: 'sluts', category: 'sexual' },
  { word: 'sl_ut', category: 'sexual' },
  { word: 'slutty', category: 'sexual' },
  { word: 'cocks', category: 'sexual' },
  { word: 'c0ck', category: 'sexual' },
  { word: 'c0cks', category: 'sexual' },
  { word: 'cunts', category: 'sexual' },
  { word: 'c_u_n_t', category: 'sexual' },
  { word: 'vaginas', category: 'sexual' },
  { word: 'v4gina', category: 'sexual' },
  { word: 'sperms', category: 'sexual' },
  { word: 'masturbating', category: 'sexual' },
  { word: 'blowjobs', category: 'sexual' },
  { word: 'bl0wjob', category: 'sexual' },
  { word: 'handjob', category: 'sexual' },
  { word: 'handjobs', category: 'sexual' },
  { word: 'gangbang', category: 'sexual' },
  { word: 'gangbangs', category: 'sexual' },
  { word: 'threesome', category: 'sexual' },
  { word: 'threesomes', category: 'sexual' },
  { word: 'orgy', category: 'sexual' },
  { word: 'orgies', category: 'sexual' },
  { word: 'milf', category: 'sexual' },
  { word: 'milfs', category: 'sexual' },
  { word: 'dilf', category: 'sexual' },
  { word: 'dilfs', category: 'sexual' },
  { word: 'bastardize', category: 'sexual' },
  { word: 'hardcore', category: 'sexual' },
  { word: 'erotic', category: 'sexual' },
  { word: 'erotica', category: 'sexual' },
  { word: 'érotique', category: 'sexual' },
  { word: 'swinger', category: 'sexual' },
  { word: 'swingers', category: 'sexual' },
  { word: 'sex', category: 'sexual' },
  { word: 'sexe', category: 'sexual' },
  { word: 'sexes', category: 'sexual' },
  { word: 'sexy', category: 'sexual' },
  { word: 'sexualise', category: 'sexual' },
  { word: 'sexualised', category: 'sexual' },
  { word: 'sexualiser', category: 'sexual' },
  { word: 'violer', category: 'sexual' },
  { word: 'violé', category: 'sexual' },
  { word: 'violée', category: 'sexual' },
  { word: 'violés', category: 'sexual' },
  { word: 'viols', category: 'sexual' },
  { word: 'viol', category: 'sexual' },
  { word: 'rape', category: 'sexual' },
  { word: 'raped', category: 'sexual' },
  { word: 'raping', category: 'sexual' },
  { word: 'rapist', category: 'sexual' },
  { word: 'rapists', category: 'sexual' },
  { word: 'r4pe', category: 'sexual' },
  { word: 'agression sexuelle', category: 'sexual' },
  { word: 'agressions sexuelles', category: 'sexual' },
  { word: 'harcèlement sexuel', category: 'sexual' },
  { word: 'sexual harassment', category: 'sexual' },
  { word: 'sexual assault', category: 'sexual' },
  { word: 'sexual assaults', category: 'sexual' },
  { word: 'voyeur', category: 'sexual' },
  { word: 'voyeurs', category: 'sexual' },
  { word: 'fetish', category: 'sexual' },
  { word: 'fétichisme', category: 'sexual' },
  { word: 'fétiche', category: 'sexual' },
  { word: 'bds m', category: 'sexual' },
  { word: 'bdsm', category: 'sexual' },
  { word: 'bondage', category: 'sexual' },
  { word: 'sadomasochisme', category: 'sexual' },
  { word: 'sadomasochism', category: 'sexual' },
  { word: 'escort', category: 'sexual' },
  { word: 'escorte', category: 'sexual' },
  { word: 'escorts', category: 'sexual' },
  { word: 'prostituée', category: 'sexual' },
  { word: 'prostitué', category: 'sexual' },
  { word: 'prostitutes', category: 'sexual' },
  { word: 'prostitute', category: 'sexual' },
  { word: 'prostitution', category: 'sexual' },
  { word: 'gigolo', category: 'sexual' },
  { word: 'gigolos', category: 'sexual' },
  { word: 'michto', category: 'sexual' },
  { word: 'michtonneuse', category: 'sexual' },
  { word: 'michtonneuses', category: 'sexual' },
  { word: 'baisodrome', category: 'sexual' },
  { word: 'tringler', category: 'sexual' },
  { word: 'tringlé', category: 'sexual' },
  { word: 'niquer', category: 'sexual' },
  { word: 'nique', category: 'sexual' },
  { word: 'niqué', category: 'sexual' },
  { word: 'niques', category: 'sexual' },
  { word: 'n1quer', category: 'sexual' },
  { word: 'baiser', category: 'sexual' },
  { word: 'baise', category: 'sexual' },
  { word: 'baisé', category: 'sexual' },
  { word: 'baisent', category: 'sexual' },
  { word: 'baisou', category: 'sexual' },
  { word: 'foutre', category: 'sexual' },
  { word: 'foutu', category: 'sexual' },
  { word: 'foutue', category: 'sexual' },
  { word: 'foutre-dieu', category: 'sexual' },
  { word: 'juter', category: 'sexual' },
  { word: 'jute', category: 'sexual' },
  { word: 'juteux', category: 'sexual' },
  { word: 'juteuse', category: 'sexual' },
  { word: 'boule', category: 'sexual' },
  { word: 'boules', category: 'sexual' },
  { word: 'fesses', category: 'sexual' },
  { word: 'fesse', category: 'sexual' },
  { word: 'cul', category: 'sexual' },
  { word: 'culs', category: 'sexual' },
  { word: 'ass', category: 'sexual' },
  { word: 'asses', category: 'sexual' },
  { word: 'butt', category: 'sexual' },
  { word: 'butts', category: 'sexual' },
  { word: 'booty', category: 'sexual' },
  { word: 'booties', category: 'sexual' },
  { word: 'boobs', category: 'sexual' },
  { word: 'boob', category: 'sexual' },
  { word: 'tits', category: 'sexual' },
  { word: 'tit', category: 'sexual' },
  { word: 'teton', category: 'sexual' },
  { word: 'téton', category: 'sexual' },
  { word: 'tetons', category: 'sexual' },
  { word: 'tétons', category: 'sexual' },
  { word: 'nipple', category: 'sexual' },
  { word: 'nipples', category: 'sexual' },
  { word: 'titsout', category: 'sexual' },
  { word: 'topless', category: 'sexual' },
  { word: 'sans-haut', category: 'sexual' },

  // --- LGBTPHOBIA ---
  { word: 'pédés', category: 'lgbtphobia' },
  { word: 'pedés', category: 'lgbtphobia' },
  { word: 'p3de', category: 'lgbtphobia' },
  { word: 'p3dés', category: 'lgbtphobia' },
  { word: 'p-é-d-é', category: 'lgbtphobia' },
  { word: 'tarlouzes', category: 'lgbtphobia' },
  { word: 'tapettes', category: 'lgbtphobia' },
  { word: 'tapette-cul', category: 'lgbtphobia' },
  { word: 't4pette', category: 'lgbtphobia' },
  { word: 'goudous', category: 'lgbtphobia' },
  { word: 'gouines', category: 'lgbtphobia' },
  { word: 'g0uine', category: 'lgbtphobia' },
  { word: 'faggots', category: 'lgbtphobia' },
  { word: 'fagots', category: 'lgbtphobia' },
  { word: 'fag0t', category: 'lgbtphobia' },
  { word: 'fag0ts', category: 'lgbtphobia' },
  { word: 'f4g', category: 'lgbtphobia' },
  { word: 'f4gs', category: 'lgbtphobia' },
  { word: 'fags', category: 'lgbtphobia' },
  { word: 'dykes', category: 'lgbtphobia' },
  { word: 'd0yke', category: 'lgbtphobia' },
  { word: 'homophobes', category: 'lgbtphobia' },
  { word: 'homophobia', category: 'lgbtphobia' },
  { word: 'transphobes', category: 'lgbtphobia' },
  { word: 'transphobia', category: 'lgbtphobia' },
  { word: 'trannys', category: 'lgbtphobia' },
  { word: 'trannie', category: 'lgbtphobia' },
  { word: 'trannies', category: 'lgbtphobia' },
  { word: 'lesbophobe', category: 'lgbtphobia' },
  { word: 'lesbophobia', category: 'lgbtphobia' },
  { word: 'lesbophobie', category: 'lgbtphobia' },
  { word: 'biphobe', category: 'lgbtphobia' },
  { word: 'biphobie', category: 'lgbtphobia' },
  { word: 'biphobia', category: 'lgbtphobia' },
  { word: 'lgbtphobes', category: 'lgbtphobia' },
  { word: 'lgbtphobie', category: 'lgbtphobia' },
  { word: 'queerbaiting', category: 'lgbtphobia' },
  { word: 'shemale', category: 'lgbtphobia' },
  { word: 'shemales', category: 'lgbtphobia' },
  { word: 'ladyboy', category: 'lgbtphobia' },
  { word: 'ladyboys', category: 'lgbtphobia' },
  { word: 'garlouze', category: 'lgbtphobia' },
  { word: 'enculeur de mouches', category: 'lgbtphobia' },
  { word: 'pd', category: 'lgbtphobia' },
  { word: 'pds', category: 'lgbtphobia' },
  { word: 'queer-trash', category: 'lgbtphobia' },

  // --- HATE & FASCISM ---
  { word: 'nazis', category: 'hate' },
  { word: 'n4zi', category: 'hate' },
  { word: 'n4zis', category: 'hate' },
  { word: 'neo-nazi', category: 'hate' },
  { word: 'neonazi', category: 'hate' },
  { word: 'neo-nazis', category: 'hate' },
  { word: 'neonazis', category: 'hate' },
  { word: 'adolf', category: 'hate' },
  { word: 'adolf hitler', category: 'hate' },
  { word: 'swastikas', category: 'hate' },
  { word: 'fascistes', category: 'hate' },
  { word: 'fascism', category: 'hate' },
  { word: 'fascisme', category: 'hate' },
  { word: 'facho', category: 'hate' },
  { word: 'fachos', category: 'hate' },
  { word: 'fachisme', category: 'hate' },
  { word: 'fachistes', category: 'hate' },
  { word: 'antisemite', category: 'hate' },
  { word: 'antisemites', category: 'hate' },
  { word: 'antisémites', category: 'hate' },
  { word: 'antisemitisme', category: 'hate' },
  { word: 'antisémitisme', category: 'hate' },
  { word: 'antisemitism', category: 'hate' },
  { word: 'croix gammee', category: 'hate' },
  { word: 'croix-gammee', category: 'hate' },
  { word: 'croix-gammée', category: 'hate' },
  { word: 'mein kampf', category: 'hate' },
  { word: 'ku-klux-klan', category: 'hate' },
  { word: 'kukluxklan', category: 'hate' },
  { word: 'suprématistes', category: 'hate' },
  { word: 'suprématie', category: 'hate' },
  { word: 'supremacy', category: 'hate' },
  { word: 'white supremacy', category: 'hate' },
  { word: 'white supremacist', category: 'hate' },
  { word: 'white supremacists', category: 'hate' },
  { word: 'suprémaciste blanc', category: 'hate' },
  { word: 'suprémacistes blancs', category: 'hate' },
  { word: 'black power', category: 'hate' },
  { word: 'holocauste', category: 'hate' },
  { word: 'holocaust', category: 'hate' },
  { word: 'shoah', category: 'hate' },
  { word: 'revisionniste', category: 'hate' },
  { word: 'révisionniste', category: 'hate' },
  { word: 'revisionnistes', category: 'hate' },
  { word: 'révisionnistes', category: 'hate' },
  { word: 'revisionism', category: 'hate' },
  { word: 'negationniste', category: 'hate' },
  { word: 'négationniste', category: 'hate' },
  { word: 'negationnistes', category: 'hate' },
  { word: 'négationnistes', category: 'hate' },
  { word: 'negationnisme', category: 'hate' },
  { word: 'négationnisme', category: 'hate' },
  { word: 'genocidaire', category: 'hate' },
  { word: 'génocidaire', category: 'hate' },
  { word: 'genocidaires', category: 'hate' },
  { word: 'génocidaires', category: 'hate' },
  { word: 'gestapo', category: 'hate' },
  { word: 'ss-officer', category: 'hate' },
  { word: 'waffen-ss', category: 'hate' },
  { word: 'waffenss', category: 'hate' },
  { word: 'aryen', category: 'hate' },
  { word: 'aryens', category: 'hate' },
  { word: 'aryan', category: 'hate' },
  { word: 'aryans', category: 'hate' },
  { word: 'fascio', category: 'hate' },
  { word: 'mussolini', category: 'hate' },
  { word: 'salazar', category: 'hate' },
  { word: 'francoism', category: 'hate' },
  { word: 'francoiste', category: 'hate' },
  { word: 'petain', category: 'hate' },
  { word: 'pétain', category: 'hate' },
  { word: 'petainiste', category: 'hate' },
  { word: 'pétainiste', category: 'hate' },
  { word: 'petainistes', category: 'hate' },
  { word: 'pétainistes', category: 'hate' },
  { word: 'collaborateur', category: 'hate' },
  { word: 'collabo', category: 'hate' },
  { word: 'collabos', category: 'hate' },
  { word: 'collaborateurs', category: 'hate' },
  { word: 'vichy regime', category: 'hate' },
  { word: 'regime de vichy', category: 'hate' },
  { word: 'régime de vichy', category: 'hate' },

  // --- GENERAL INSULTS & OBSCENITIES ---
  { word: 'cons', category: 'insult' },
  { word: 'connards', category: 'insult' },
  { word: 'c0nnard', category: 'insult' },
  { word: 'c0nnards', category: 'insult' },
  { word: 'connasses', category: 'insult' },
  { word: 'c0nnasse', category: 'insult' },
  { word: 'salopards', category: 'insult' },
  { word: 's4lopard', category: 'insult' },
  { word: 's4lopards', category: 'insult' },
  { word: 'fdps', category: 'insult' },
  { word: 'f.d.p', category: 'insult' },
  { word: 'f_d_p', category: 'insult' },
  { word: 'fils de putes', category: 'insult' },
  { word: 'merdes', category: 'insult' },
  { word: 'merdeux', category: 'insult' },
  { word: 'merdeuse', category: 'insult' },
  { word: 'm3rde', category: 'insult' },
  { word: 'enculés', category: 'insult' },
  { word: 'encules', category: 'insult' },
  { word: 'enculées', category: 'insult' },
  { word: 'enculees', category: 'insult' },
  { word: '3nculé', category: 'insult' },
  { word: '3ncule', category: 'insult' },
  { word: 'abrutis', category: 'insult' },
  { word: 'abrutie', category: 'insult' },
  { word: 'abruties', category: 'insult' },
  { word: 'débiles', category: 'insult' },
  { word: 'debiles', category: 'insult' },
  { word: 'd3bile', category: 'insult' },
  { word: 'd3biles', category: 'insult' },
  { word: 'mongols', category: 'insult' },
  { word: 'mongoliens', category: 'insult' },
  { word: 'mongolienne', category: 'insult' },
  { word: 'mongoliennes', category: 'insult' },
  { word: 'm0ngol', category: 'insult' },
  { word: 'tocards', category: 'insult' },
  { word: 'tocarde', category: 'insult' },
  { word: 'tocardes', category: 'insult' },
  { word: 'crevards', category: 'insult' },
  { word: 'crevarda', category: 'insult' },
  { word: 'crevarde', category: 'insult' },
  { word: 'bâtards', category: 'insult' },
  { word: 'batards', category: 'insult' },
  { word: 'bâtarde', category: 'insult' },
  { word: 'batarde', category: 'insult' },
  { word: 'b4tard', category: 'insult' },
  { word: 'gogols', category: 'insult' },
  { word: 'g0g0l', category: 'insult' },
  { word: 'g0g0ls', category: 'insult' },
  { word: 'bouffons', category: 'insult' },
  { word: 'bouffonne', category: 'insult' },
  { word: 'bouffonnes', category: 'insult' },
  { word: 'assholes', category: 'insult' },
  { word: '4sshole', category: 'insult' },
  { word: '4ssholes', category: 'insult' },
  { word: 'bastards', category: 'insult' },
  { word: 'b4stard', category: 'insult' },
  { word: 'motherfuckers', category: 'insult' },
  { word: 'm0therfucker', category: 'insult' },
  { word: 'm0therfuckers', category: 'insult' },
  { word: 'muthafucka', category: 'insult' },
  { word: 'muthafuckas', category: 'insult' },
  { word: 'idiots', category: 'insult' },
  { word: 'idiote', category: 'insult' },
  { word: 'idiotes', category: 'insult' },
  { word: '1diot', category: 'insult' },
  { word: '1diots', category: 'insult' },
  { word: 'retards', category: 'insult' },
  { word: 'retarded', category: 'insult' },
  { word: 'r3tard', category: 'insult' },
  { word: 'r3tards', category: 'insult' },
  { word: 'dumbasses', category: 'insult' },
  { word: 'dumb', category: 'insult' },
  { word: 'jerks', category: 'insult' },
  { word: 'j3rk', category: 'insult' },
  { word: 'pieces of shit', category: 'insult' },
  { word: 'crap', category: 'insult' },
  { word: 'crappy', category: 'insult' },
  { word: 'shit', category: 'insult' },
  { word: 'shits', category: 'insult' },
  { word: 'shitty', category: 'insult' },
  { word: 'sh1t', category: 'insult' },
  { word: 'fuck', category: 'insult' },
  { word: 'fucks', category: 'insult' },
  { word: 'fucking', category: 'insult' },
  { word: 'fucked', category: 'insult' },
  { word: 'fucker', category: 'insult' },
  { word: 'fuckers', category: 'insult' },
  { word: 'f_u_c_k', category: 'insult' },
  { word: 'f*ck', category: 'insult' },
  { word: 'f**k', category: 'insult' },
  { word: 'bitch', category: 'insult' },
  { word: 'bitches', category: 'insult' },
  { word: 'b1tch', category: 'insult' },
  { word: 'b1tches', category: 'insult' },
  { word: 'son of a bitch', category: 'insult' },
  { word: 'son of a b1tch', category: 'insult' },
  { word: 'sons of bitches', category: 'insult' },
  { word: 'crapula', category: 'insult' },
  { word: 'crapule', category: 'insult' },
  { word: 'crapules', category: 'insult' },
  { word: 'ordure', category: 'insult' },
  { word: 'ordures', category: 'insult' },
  { word: 'racaille', category: 'insult' },
  { word: 'racailles', category: 'insult' },
  { word: 'voyou', category: 'insult' },
  { word: 'voyous', category: 'insult' },
  { word: 'pourceau', category: 'insult' },
  { word: 'pourceaux', category: 'insult' },
  { word: 'pourceau-dieu', category: 'insult' },
  { word: 'porc', category: 'insult' },
  { word: 'porcs', category: 'insult' },
  { word: 'chienne', category: 'insult' },
  { word: 'chiennes', category: 'insult' },
  { word: 'saligaud', category: 'insult' },
  { word: 'saligauds', category: 'insult' },
  { word: 'salop', category: 'insult' },
  { word: 'salops', category: 'insult' },
  { word: 'cretin', category: 'insult' },
  { word: 'crétin', category: 'insult' },
  { word: 'cretins', category: 'insult' },
  { word: 'crétins', category: 'insult' },
  { word: 'cretine', category: 'insult' },
  { word: 'crétine', category: 'insult' },
  { word: 'stupide', category: 'insult' },
  { word: 'stupides', category: 'insult' },
  { word: 'imbecile', category: 'insult' },
  { word: 'imbécile', category: 'insult' },
  { word: 'imbeciles', category: 'insult' },
  { word: 'imbéciles', category: 'insult' },
  { word: 'ignare', category: 'insult' },
  { word: 'ignares', category: 'insult' },
  { word: 'va te faire', category: 'insult' },
  { word: 'va te faire foutre', category: 'insult' },
  { word: 'va t faire foutre', category: 'insult' },
  { word: 'mange tes morts', category: 'insult' },
  { word: 'mange tes m0rts', category: 'insult' },
  { word: 'casse toi', category: 'insult' },
  { word: 'casse-toi', category: 'insult' },
  { word: 'degage', category: 'insult' },
  { word: 'dégage', category: 'insult' },
  { word: 'nique ta mere', category: 'insult' },
  { word: 'nique ta méré', category: 'insult' },
  { word: 'nique ta m3re', category: 'insult' },
  { word: 'nique ta race', category: 'insult' },
  { word: 'nique ta r4ce', category: 'insult' },
  { word: 'nique ton pere', category: 'insult' },
  { word: 'nique ton p3re', category: 'insult' },
  { word: 'baise ta mere', category: 'insult' },
  { word: 'baise ta m3re', category: 'insult' },
  { word: 'chier', category: 'insult' },
  { word: 'chie', category: 'insult' },
  { word: 'chieur', category: 'insult' },
  { word: 'chieuse', category: 'insult' },
  { word: 'chieurs', category: 'insult' },
  { word: 'chiant', category: 'insult' },
  { word: 'chiante', category: 'insult' },
  { word: 'fait chier', category: 'insult' },
  { word: 'fout la merde', category: 'insult' },
  { word: 'fouteur de merde', category: 'insult' },
  { word: 'fouteuse de merde', category: 'insult' },
  { word: 'fouteurs de merde', category: 'insult' },
  { word: 'trou du cul', category: 'insult' },
  { word: 'trouduc', category: 'insult' },
  { word: 'trou d cul', category: 'insult' },
  { word: 'trou-du-cul', category: 'insult' },
  { word: 'trous du cul', category: 'insult' },
  { word: 'ass wipe', category: 'insult' },
  { word: 'asswipe', category: 'insult' },
  { word: 'butt wipe', category: 'insult' },
  { word: 'douchebag', category: 'insult' },
  { word: 'douchebags', category: 'insult' },
  { word: 'scumbag', category: 'insult' },
  { word: 'scumbags', category: 'insult' },
  { word: 'sucker', category: 'insult' },
  { word: 'suckers', category: 'insult' },
  { word: 'suck my dick', category: 'insult' },
  { word: 'suck my cock', category: 'insult' },
  { word: 'suce ma bite', category: 'insult' },
  { word: 'suce ma b1te', category: 'insult' },
  { word: 'suce mon penis', category: 'insult' },
  { word: 'suce mon pénis', category: 'insult' },
  { word: 'va sucer', category: 'insult' },
  { word: 'pisse', category: 'insult' },
  { word: 'pisser', category: 'insult' },
  { word: 'pisseur', category: 'insult' },
  { word: 'pisseux', category: 'insult' },
  { word: 'pisseuse', category: 'insult' },
  { word: 'cuntbag', category: 'insult' },
  { word: 'clitbag', category: 'insult' },
  { word: 'wanker', category: 'insult' },
  { word: 'wankers', category: 'insult' },
  { word: 'twat', category: 'insult' },
  { word: 'twats', category: 'insult' },
  { word: 'tosser', category: 'insult' },
  { word: 'tossers', category: 'insult' },
  { word: 'bellend', category: 'insult' },
  { word: 'bellends', category: 'insult' },
  { word: 'bollocks', category: 'insult' },
  { word: 'bollock', category: 'insult' },
  { word: 'prick', category: 'insult' },
  { word: 'pricks', category: 'insult' },
  { word: 'plonker', category: 'insult' },
  { word: 'plonkers', category: 'insult' },
  { word: 'muppet', category: 'insult' },
  { word: 'muppets', category: 'insult' },
  { word: 'dipshit', category: 'insult' },
  { word: 'dipshits', category: 'insult' },
  { word: 'jackass', category: 'insult' },
  { word: 'jackasses', category: 'insult' },
  { word: 'bloody hell', category: 'insult' },
  { word: 'goddammit', category: 'insult' },
  { word: 'goddamn', category: 'insult' },
  { word: 'craphead', category: 'insult' },
  { word: 'shithead', category: 'insult' },
  { word: 'shitheads', category: 'insult' },
  { word: 'dickhead', category: 'insult' },
  { word: 'dickheads', category: 'insult' },
  { word: 'pussy whipping', category: 'insult' },
  { word: 'pussywhipped', category: 'insult' },
  { word: 'badtripper', category: 'insult' },
  { word: 'chieur-né', category: 'insult' },
  { word: 'brise-burnes', category: 'insult' },
  { word: 'casse-couilles', category: 'insult' },
  { word: 'casse-couille', category: 'insult' },
  { word: 'casse-bonbons', category: 'insult' },
  { word: 'casse-burnes', category: 'insult' },
  { word: 'casse couilles', category: 'insult' },
  { word: 'casse couille', category: 'insult' },
  { word: 'broute-minou', category: 'insult' },
  { word: 'broute minou', category: 'insult' },
  { word: 'leche-cul', category: 'insult' },
  { word: 'lèche-cul', category: 'insult' },
  { word: 'lèche cul', category: 'insult' },
  { word: 'leche cul', category: 'insult' },
  { word: 'leche-botte', category: 'insult' },
  { word: 'lèche-botte', category: 'insult' },
  { word: 'lèche-bottes', category: 'insult' },
  { word: 'leche-bottes', category: 'insult' },
  { word: 'larbin', category: 'insult' },
  { word: 'larbins', category: 'insult' },
  { word: 'collabo-trash', category: 'insult' },
  { word: 'lechecul', category: 'insult' },
  { word: 'lechebottes', category: 'insult' },
  { word: 'faillot', category: 'insult' },
  { word: 'faillots', category: 'insult' },
  { word: 'fayot', category: 'insult' },
  { word: 'fayots', category: 'insult' },
  { word: 'fayoter', category: 'insult' },
  { word: 'suce-boules', category: 'insult' },
  { word: 'suce boules', category: 'insult' },
  { word: 'suce-boule', category: 'insult' },
  { word: 'suce boule', category: 'insult' },
  { word: 'suceboule', category: 'insult' },
  { word: 'suceboules', category: 'insult' },
  { word: 'lèche-bourses', category: 'insult' },
  { word: 'leche-bourses', category: 'insult' },
  { word: 'lechebourses', category: 'insult' },
  { word: 'suceur', category: 'insult' },
  { word: 'suceurs', category: 'insult' },
  { word: 'suceuse', category: 'insult' },
  { word: 'suceuses', category: 'insult' },
  { word: 'tête de nœud', category: 'insult' },
  { word: 'tête de noeud', category: 'insult' },
  { word: 'tete de noeud', category: 'insult' },
  { word: 'tête de nœuds', category: 'insult' },
  { word: 'tete de noeuds', category: 'insult' },
  { word: 'tête de con', category: 'insult' },
  { word: 'tete de con', category: 'insult' },
  { word: 'têtes de con', category: 'insult' },
  { word: 'tetes de con', category: 'insult' },
  { word: 'tête de cul', category: 'insult' },
  { word: 'tete de cul', category: 'insult' },
  { word: 'tête de gland', category: 'insult' },
  { word: 'tete de gland', category: 'insult' },
  { word: 'gland', category: 'insult' },
  { word: 'glands', category: 'insult' },
  { word: 'glandeur', category: 'insult' },
  { word: 'glandeuse', category: 'insult' },
  { word: 'glandeurs', category: 'insult' },
  { word: 'glandeuses', category: 'insult' },
  { word: 'couillon', category: 'insult' },
  { word: 'couillons', category: 'insult' },
  { word: 'couillonne', category: 'insult' },
  { word: 'couillonnes', category: 'insult' },
  { word: 'crétiniser', category: 'insult' },
  { word: 'crétinisé', category: 'insult' },
  { word: 'abrutissement', category: 'insult' },
  { word: 'dégénéré', category: 'insult' },
  { word: 'degenere', category: 'insult' },
  { word: 'dégénérée', category: 'insult' },
  { word: 'degeneree', category: 'insult' },
  { word: 'dégénérés', category: 'insult' },
  { word: 'degeneres', category: 'insult' },
  { word: 'dégénérées', category: 'insult' },
  { word: 'degenerees', category: 'insult' },
  { word: 'degeneracy', category: 'insult' },
  { word: 'degenerate', category: 'insult' },
  { word: 'degenerates', category: 'insult' },
  { word: 'knobhead', category: 'insult' },
  { word: 'knobheads', category: 'insult' },
  { word: 'bell-end', category: 'insult' },
  { word: 'bell-ends', category: 'insult' },
  { word: 'ass-hole', category: 'insult' },
  { word: 'ass-holes', category: 'insult' },
  { word: 'cunt-face', category: 'insult' },
  { word: 'cuntface', category: 'insult' },
  { word: 'cunt-faces', category: 'insult' },
  { word: 'shit-head', category: 'insult' },
  { word: 'shit-heads', category: 'insult' },
  { word: 'dick-head', category: 'insult' },
  { word: 'dick-heads', category: 'insult' },
  { word: 'butt-head', category: 'insult' },
  { word: 'butthead', category: 'insult' },
  { word: 'butt-heads', category: 'insult' },
  { word: 'pecker', category: 'insult' },
  { word: 'peckers', category: 'insult' },
  { word: 'fuckhead', category: 'insult' },
  { word: 'fuckheads', category: 'insult' },
  { word: 'fuck-head', category: 'insult' },
  { word: 'fuck-heads', category: 'insult' },
  { word: 'fuckface', category: 'insult' },
  { word: 'fuck-face', category: 'insult' },
  { word: 'fuckfaces', category: 'insult' },
  { word: 'fuckwit', category: 'insult' },
  { word: 'fuckwits', category: 'insult' },
  { word: 'fuck-wit', category: 'insult' },
  { word: 'fuck-wits', category: 'insult' },
  { word: 'dip-shit', category: 'insult' },
  { word: 'dip-shits', category: 'insult' },
  { word: 'dumb-ass', category: 'insult' },
  { word: 'dumb-asses', category: 'insult' },
  { word: 'numbskull', category: 'insult' },
  { word: 'numbskulls', category: 'insult' },
  { word: 'bonehead', category: 'insult' },
  { word: 'boneheads', category: 'insult' },
  { word: 'airhead', category: 'insult' },
  { word: 'airheads', category: 'insult' },
  { word: 'sap', category: 'insult' },
  { word: 'saps', category: 'insult' },
  { word: 'dunderhead', category: 'insult' },
  { word: 'dunderheads', category: 'insult' },
  { word: 'blockhead', category: 'insult' },
  { word: 'blockheads', category: 'insult' },
  { word: 'nincompoop', category: 'insult' },
  { word: 'nincompoops', category: 'insult' },
  { word: 'clown', category: 'insult' },
  { word: 'clowns', category: 'insult' },
  { word: 'bâtardise', category: 'insult' },
  { word: 'batardise', category: 'insult' },
  { word: 'bâtardises', category: 'insult' },
  { word: 'charlatan', category: 'insult' },
  { word: 'charlatans', category: 'insult' },
  { word: 'imposteur', category: 'insult' },
  { word: 'imposteurs', category: 'insult' },
  { word: 'rapace', category: 'insult' },
  { word: 'rapaces', category: 'insult' },
  { word: 'avare', category: 'insult' },
  { word: 'avares', category: 'insult' },
  { word: 'pingre', category: 'insult' },
  { word: 'pingres', category: 'insult' },
  { word: 'mégère', category: 'insult' },
  { word: 'megere', category: 'insult' },
  { word: 'mégères', category: 'insult' },
  { word: 'harpies', category: 'insult' },
  { word: 'harpie', category: 'insult' },
  { word: 'vieille bique', category: 'insult' },
  { word: 'vieille boche', category: 'insult' },
  { word: 'boche', category: 'insult' },
  { word: 'boches', category: 'insult' },
  { word: 'chleuh', category: 'insult' },
  { word: 'chleuhs', category: 'insult' },
  { word: 'rosbif', category: 'insult' },
  { word: 'rosbifs', category: 'insult' },
  { word: 'yankee', category: 'insult' },
  { word: 'yankees', category: 'insult' },
  { word: 'ricain', category: 'insult' },
  { word: 'ricains', category: 'insult' },
  { word: 'portougalais', category: 'insult' },
  { word: 'espagoing', category: 'insult' },
  { word: 'polak', category: 'insult' },
  { word: 'polaks', category: 'insult' },
  { word: 'youpin', category: 'insult' },
  { word: 'youpins', category: 'insult' },
  { word: 'youdi', category: 'insult' },
  { word: 'youdies', category: 'insult' },
  { word: 'feuj', category: 'insult' },
  { word: 'feujs', category: 'insult' },
  { word: 'rebeu', category: 'insult' },
  { word: 'rebeus', category: 'insult' },
  { word: 'renoi', category: 'insult' },
  { word: 'renois', category: 'insult' },
  { word: 'babtou', category: 'insult' },
  { word: 'babtous', category: 'insult' },
  { word: 'toubab', category: 'insult' },
  { word: 'toubabs', category: 'insult' },
  { word: 'gwer', category: 'insult' },
  { word: 'gwers', category: 'insult' },
  { word: 'kouffar', category: 'insult' },
  { word: 'kuffar', category: 'insult' },
  { word: 'koufr', category: 'insult' },
  { word: 'kuffr', category: 'insult' },
];

async function main() {
  console.log(`🌱 Seeding ${DEFAULT_FEEDS.length} flux RSS pour le serveur ${guildId}...`);

  // Ensure guild exists
  await prisma.guild.upsert({
    where: { id: guildId },
    update: {},
    create: { id: guildId },
  });

  let created = 0;
  let skipped = 0;

  for (const feed of DEFAULT_FEEDS) {
    const existing = await prisma.feed.findFirst({ where: { guildId, url: feed.url } });
    if (existing) { skipped++; continue; }

    await prisma.feed.create({
      data: {
        guildId,
        name: feed.name,
        url: feed.url,
        category: feed.category,
        language: feed.language,
        enabled: true,
      },
    });
    created++;
    console.log(`  ✅ ${feed.name}`);
  }

  console.log(`\n🌱 Seeding ${DEFAULT_DEVELOPER_EXCUSES.length} excuses développeur...`);

  let excusesCreated = 0;
  let excusesSkipped = 0;

  for (const excuse of DEFAULT_DEVELOPER_EXCUSES) {
    const existing = await prisma.developerExcuse.findFirst({ where: { text: excuse, language: 'fr' } });
    if (existing) {
      excusesSkipped++;
      continue;
    }

    await prisma.developerExcuse.create({
      data: {
        text: excuse,
        language: 'fr',
      },
    });
    excusesCreated++;
    console.log(`  ✅ ${excuse}`);
  }

  console.log(`\n🌱 Seeding ${DEFAULT_DAILY_ALGO_PROBLEMS.length} problèmes de Daily Algo...`);

  let algoCreated = 0;
  let algoSkipped = 0;

  for (const problem of DEFAULT_DAILY_ALGO_PROBLEMS) {
    const existing = await prisma.dailyAlgoProblem.findFirst({ where: { title: problem.title, language: 'fr' } });
    if (existing) {
      algoSkipped++;
      continue;
    }

    await prisma.dailyAlgoProblem.create({
      data: {
        title: problem.title,
        description: problem.description,
        solution: problem.solution,
        difficulty: problem.difficulty,
        language: 'fr',
        functionName: problem.functionName,
        functionArgs: problem.functionArgs,
        unitTests: problem.unitTests,
        allowedLanguages: problem.allowedLanguages,
      },
    });
    algoCreated++;
    console.log(`  ✅ ${problem.title}`);
  }

  console.log(`\n🌱 Seeding ${DEFAULT_CODE_POLICE_RULES.length} règles de Police du code...`);

  let codePoliceCreated = 0;
  let codePoliceSkipped = 0;

  for (const rule of DEFAULT_CODE_POLICE_RULES) {
    const existing = await prisma.codePoliceRule.findUnique({ where: { key: rule.key } });
    if (existing) {
      codePoliceSkipped++;
      continue;
    }

    await prisma.codePoliceRule.create({
      data: {
        key: rule.key,
        guildId: null,
        category: rule.category,
        matchType: rule.matchType,
        language: rule.language,
        pattern: rule.pattern,
        label: rule.label,
        feedback: rule.feedback,
        severity: rule.severity,
        enabled: true,
      },
    });

    codePoliceCreated++;
    console.log(`  ✅ ${rule.label}`);
  }

  console.log(`\n🌱 Seeding ${DEFAULT_BANNED_WORDS.length} mots bannis globaux...`);

  let bannedWordsCreated = 0;
  let bannedWordsSkipped = 0;

  for (const item of DEFAULT_BANNED_WORDS) {
    const existing = await prisma.bannedWord.findFirst({
      where: {
        guildId: null,
        word: item.word,
      },
    });
    if (existing) {
      bannedWordsSkipped++;
      continue;
    }

    await prisma.bannedWord.create({
      data: {
        guildId: null,
        word: item.word,
        category: item.category,
        enabled: true,
      },
    });
    bannedWordsCreated++;
    console.log(`  ✅ [${item.category.toUpperCase()}] ${item.word}`);
  }

  console.log(`\n✨ Seed terminé : ${created} flux créés, ${skipped} ignorés, ${excusesCreated} excuses créées, ${excusesSkipped} excuses ignorées, ${algoCreated} problèmes d'algo créés, ${algoSkipped} problèmes ignorés, ${codePoliceCreated} règles de Police du code créées, ${codePoliceSkipped} ignorées, ${bannedWordsCreated} mots bannis globaux créés, ${bannedWordsSkipped} ignorés`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
