import path from 'node:path';
import { config as loadEnv } from 'dotenv';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

loadEnv({ path: path.resolve(import.meta.dir, '../../.env') });
loadEnv({ path: path.resolve(import.meta.dir, '../../../.env') });

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error('❌ DATABASE_URL non défini dans .env');
  process.exit(1);
}

const adapter = new PrismaPg({ connectionString });

const prisma = new PrismaClient({ adapter });

const GUILD_ID = process.env.GUILD_ID;
if (!GUILD_ID) {
  console.error('❌ GUILD_ID non défini dans .env');
  process.exit(1);
}

const guildId: string = GUILD_ID;

const DEFAULT_DEVELOPER_EXCUSES = [
  // ==========================================
  // 1. LES CLASSIQUES INCONTOURNABLES (0-20)
  // ==========================================
  { text: "Ça fonctionnait sur ma machine.", category: "classiques" },
  { text: "C'est un problème de cache.", category: "classiques" },
  { text: "C'est une fonctionnalité, pas un bug.", category: "classiques" },
  { text: "L'API externe était indisponible.", category: "classiques" },
  { text: "Je pense que c'est un souci de localStorage.", category: "classiques" },
  { text: "Tout dépend du timing.", category: "classiques" },
  { text: "Il faut vider le cache du navigateur.", category: "classiques" },
  { text: "Il manque un point-virgule quelque part.", category: "classiques" },
  { text: "C'est une classique condition de course.", category: "classiques" },
  { text: "Le serveur n'était pas prêt.", category: "classiques" },
  { text: "Ça marche en production, je ne sais pas pourquoi.", category: "classiques" },
  { text: "Le client n'a pas donné assez de détails.", category: "classiques" },
  { text: "C'est un problème en aval.", category: "classiques" },
  { text: "Je l'avais corrigé localement, mais j'ai oublié de commit.", category: "classiques" },
  { text: "C'est une incompatibilité de navigateur.", category: "classiques" },
  { text: "La base de données était lente ce jour-là.", category: "classiques" },
  { text: "C'est un problème de DNS. C'est TOUJOURS un problème de DNS.", category: "classiques" },
  { text: "Pourtant, tous les tests unitaires passaient au vert sur la CI.", category: "classiques" },
  { text: "Quelqu'un a dû push en force sur la branche principale sans me le dire.", category: "classiques" },
  { text: "C'est à cause de la dernière mise à jour de Node.", category: "classiques" },

  // ==========================================
  // 2. GIT, CI/CD & REVISIONS (20-70)
  // ==========================================
  { text: "J'ai un conflit de fusion (merge conflict) que je n'ai pas vu passer.", category: "git_cicd" },
  { text: "C'est la faute du rebase, ça a écrasé mes modifications.", category: "git_cicd" },
  { text: "Le webhook de GitHub n'a pas déclenché le build.", category: "git_cicd" },
  { text: "La CI est tombée en panne au milieu de l'étape de peluchage (linting).", category: "git_cicd" },
  { text: "Quelqu'un a modifié le fichier .gitignore et mon code n'est pas monté.", category: "git_cicd" },
  { text: "Le pre-commit hook a bloqué mon push, j'ai dû bypasser.", category: "git_cicd" },
  { text: "J'ai confondu ma branche de dev et la branche de prod.", category: "git_cicd" },
  { text: "Le commit est parti sur un dépôt détaché (detached HEAD).", category: "git_cicd" },
  { text: "Le serveur de intégration continue n'a pas les mêmes variables d'environnement.", category: "git_cicd" },
  { text: "C'est un problème de droits d'accès sur le token personnel de GitHub.", category: "git_cicd" },
  { text: "J'ai fait un git push --force par habitude, désolé.", category: "git_cicd" },
  { text: "Le runner GitLab n'avait plus d'espace disque disponible.", category: "git_cicd" },
  { text: "Le build a expiré (timeout) parce que la file d'attente était trop longue.", category: "git_cicd" },
  { text: "Les modules de test n'ont pas été installés sur l'agent de build.", category: "git_cicd" },
  { text: "Le fichier lock n'était pas synchronisé avec le package.json.", category: "git_cicd" },
  { text: "Mon commit a été écrasé par un commit automatique du bot de dépendances.", category: "git_cicd" },
  { text: "Le tag de version n'a pas été poussé sur le registre.", category: "git_cicd" },
  { text: "La clé SSH de la CI a expiré ce matin.", category: "git_cicd" },
  { text: "Le dépôt distant a renvoyé une erreur 503 pendant le fetch.", category: "git_cicd" },
  { text: "J'ai annulé le mauvais pipeline.", category: "git_cicd" },

  // ==========================================
  // 3. INFRASTRUCTURE, DOCKER & CLOUD (70-120)
  // ==========================================
  { text: "Docker n'a pas vidé ses volumes, l'ancien code tournait encore.", category: "infra_cloud" },
  { text: "Le pod Kubernetes est entré dans une boucle de crash infernale (CrashLoopBackOff).", category: "infra_cloud" },
  { text: "L'équilibreur de charge (Load Balancer) redirige vers une ancienne instance.", category: "infra_cloud" },
  { text: "Le certificat SSL/TLS a expiré à minuit.", category: "infra_cloud" },
  { text: "La passerelle API (API Gateway) a jeté la requête à cause d'un timeout.", category: "infra_cloud" },
  { text: "Le serveur n'avait plus d'inodes disponibles.", category: "infra_cloud" },
  { text: "AWS a restreint nos quotas d'instances ce mois-ci.", category: "infra_cloud" },
  { text: "C'est le proxy de l'entreprise qui intercepte et modifie les en-têtes HTTP.", category: "infra_cloud" },
  { text: "Le script d'initialisation de la base de données ne s'est pas lancé.", category: "infra_cloud" },
  { text: "La configuration du reverse proxy Nginx est corrompue.", category: "infra_cloud" },
  { text: "Le conteneur est à court de mémoire (OOM Killer).", category: "infra_cloud" },
  { text: "La zone de disponibilité d'AWS est actuellement en panne.", category: "infra_cloud" },
  { text: "Les variables d'environnement de Vercel n'ont pas été propagées.", category: "infra_cloud" },
  { text: "Le groupe de sécurité bloque le port requis.", category: "infra_cloud" },
  { text: "Le montage réseau NFS a sauté.", category: "infra_cloud" },
  { text: "Les logs ont saturé le disque dur du serveur applicatif.", category: "infra_cloud" },
  { text: "Le serveur de base de données a changé d'adresse IP privée.", category: "infra_cloud" },
  { text: "Le cron job ne s'est pas exécuté à l'heure prévue.", category: "infra_cloud" },
  { text: "La configuration CORS du bucket S3 rejette l'origine.", category: "infra_cloud" },
  { text: "C'est un problème de réplication de base de données à cause de la latence.", category: "infra_cloud" },

  // ==========================================
  // 4. FRONT-END, CSS & BROWSERS (120-170)
  // ==========================================
  { text: "Sur Chrome ça passe, c'est encore un coup de Safari mobile.", category: "frontend" },
  { text: "Le CSS s'est chargé après le JS, ça crée un décalage de mise en page.", category: "frontend" },
  { text: "C'est le bloqueur de pub (AdBlock) de l'utilisateur qui casse le script.", category: "frontend" },
  { text: "Le service worker a mis en cache une version cassée de l'application.", category: "frontend" },
  { text: "La police d'écriture personnalisée bloque le rendu du texte.", category: "frontend" },
  { text: "C'est une erreur d'hydratation du framework SSR.", category: "frontend" },
  { text: "L'utilisateur utilise encore Internet Explorer en mode compatibilité.", category: "frontend" },
  { text: "Le mode sombre applique des styles non gérés sur ce composant.", category: "frontend" },
  { text: "C'est un problème de densité de pixels sur les écrans Retina.", category: "frontend" },
  { text: "Le z-index de ce composant est inférieur à celui de la modale.", category: "frontend" },
  { text: "La détection tactile entre en conflit avec l'événement de clic.", category: "frontend" },
  { text: "Le redimensionnement de la fenêtre casse le layout Grid.", category: "frontend" },
  { text: "L'API d'animation n'est pas supportée sur ce modèle de smartphone.", category: "frontend" },
  { text: "Le navigateur a bloqué la lecture automatique du contenu multimédia.", category: "frontend" },
  { text: "Une extension Chrome injecte du code HTML qui détruit mon DOM.", category: "frontend" },
  { text: "La session a expiré dans le cookie, mais l'UI ne le sait pas encore.", category: "frontend" },
  { text: "L'intersection observer n'a pas détecté le défilement.", category: "frontend" },
  { text: "Les variables CSS ne sont pas interpolées correctement par ce compilateur.", category: "frontend" },
  { text: "Le rendu est cassé uniquement en mode paysage sur les tablettes.", category: "frontend" },
  { text: "L'attribut 'secure' du cookie empêche sa lecture en HTTP local.", category: "frontend" },

  // ==========================================
  // 5. BACK-END, APIS & DATA (170-220)
  // ==========================================
  { text: "L'ORM a généré une requête SQL d'une lenteur absolue.", category: "backend" },
  { text: "Le jeton JWT a expiré dix secondes trop tôt.", category: "backend" },
  { text: "La base de données a atteint son nombre maximal de connexions simultanées.", category: "backend" },
  { text: "C'est une erreur de sérialisation JSON sur un champ de date.", category: "backend" },
  { text: "Le webhook a renvoyé un statut 200 mais le corps était vide.", category: "backend" },
  { text: "Le type de données dans PostgreSQL ne correspond pas au modèle Prisma.", category: "backend" },
  { text: "C'est un problème d'encodage de caractères (UTF-8 vs ISO-8859-1).", category: "backend" },
  { text: "La requête a dépassé la taille maximale autorisée par le serveur.", category: "backend" },
  { text: "L'indexation de la base de données n'est pas encore terminée.", category: "backend" },
  { text: "Le serveur de cache Redis a été vidé inopinément.", category: "backend" },
  { text: "C'est une faille de contrainte de clé étrangère.", category: "backend" },
  { text: "La pagination renvoie une page vide si on va trop vite.", category: "backend" },
  { text: "L'API tierce a changé son schéma de réponse sans prévenir.", category: "backend" },
  { text: "Le chiffrement des données utilise un sel qui a été modifié.", category: "backend" },
  { text: "Une fuite de mémoire dans le thread principal paralyse le routeur.", category: "backend" },
  { text: "Le parseur de requêtes ne gère pas le format FormData.", category: "backend" },
  { text: "La géolocalisation par IP renvoie des coordonnées erronées.", category: "backend" },
  { text: "Le système de fichiers est en lecture seule suite à une alerte de sécurité.", category: "backend" },
  { text: "Les identifiants de la base de données de test ont fuité, elle a été bloquée.", category: "backend" },
  { text: "La file d'attente des messages (RabbitMQ) est saturée.", category: "backend" },

  // ==========================================
  // 6. ENFER DES DEPENDANCES & RUNTIMES (220-270)
  // ==========================================
  { text: "La mise à jour mineure d'un sous-package a tout cassé (breaking change).", category: "dependencies" },
  { text: "Le gestionnaire de paquets a installé une version obsolète depuis son cache.", category: "dependencies" },
  { text: "Il y a un conflit entre l'architecture x86 et ARM de ma puce.", category: "dependencies" },
  { text: "Le compilateur TypeScript refuse de build à cause d'un type 'any' caché.", category: "dependencies" },
  { text: "La version globale de Node ne correspond pas à celle spécifiée dans le projet.", category: "dependencies" },
  { text: "C'est une vulnérabilité de sécurité critique qui bloque l'installation.", category: "dependencies" },
  { text: "Le package n'est plus maintenu depuis trois ans.", category: "dependencies" },
  { text: "Le bundler (Vite/Webpack) n'arrive pas à résoudre le module ES.", category: "dependencies" },
  { text: "Le moteur d'exécution (runtime) manque de permissions système.", category: "dependencies" },
  { text: "Le fichier lock est corrompu, il faut supprimer node_modules et recommencer.", category: "dependencies" },
  { text: "Cette bibliothèque nécessite une version de Python obsolète pour compiler.", category: "dependencies" },
  { text: "Le ramasse-miettes (garbage collector) s'est déclenché au pire moment.", category: "dependencies" },
  { text: "Le package a été retiré du registre npm par son auteur.", category: "dependencies" },
  { text: "La compilation native du module C++ a échoué.", category: "dependencies" },
  { text: "Le linter refuse le déploiement pour un espace en trop en fin de ligne.", category: "dependencies" },
  { text: "La configuration Babel ne transpile pas cette syntaxe moderne.", category: "dependencies" },
  { text: "Le framework utilise une version expérimentale non documentée.", category: "dependencies" },
  { text: "Le SDK refuse de s'initialiser sans une variable d'environnement optionnelle.", category: "dependencies" },
  { text: "La dépendance a une dépendance circulaire invisible.", category: "dependencies" },
  { text: "Le compilateur a optimisé le code en supprimant la fonction essentielle.", category: "dependencies" },

  // ==========================================
  // 7. GESTION DE PROJET & SPECIFICATIONS (270-320)
  // ==========================================
  { text: "Ce cas d'usage n'était pas mentionné dans le cahier des charges.", category: "management" },
  { text: "Les spécifications ont changé pendant que je développais la fonctionnalité.", category: "management" },
  { text: "Le designer n'a pas fourni les maquettes pour la version mobile.", category: "management" },
  { text: "Le chef de projet m'a dit que ce n'était pas prioritaire.", category: "management" },
  { text: "Le client teste l'application avec des données totalement irréalistes.", category: "management" },
  { text: "J'attendais les retours de l'équipe produit avant de valider le ticket.", category: "management" },
  { text: "Ce n'est pas un bug, c'est exactement ce que le client a demandé à l'oral.", category: "management" },
  { text: "La réunion de cadrage a été annulée, j'ai codé à l'instinct.", category: "management" },
  { text: "Le ticket Jira était assigné à la mauvaise personne.", category: "management" },
  { text: "Les critères d'acceptation étaient beaucoup trop vagues.", category: "management" },
  { text: "Le flux d'utilisateurs décrit dans la spécification est impossible à réaliser.", category: "management" },
  { text: "Le client utilise un environnement de test qui n'a jamais été configuré.", category: "management" },
  { text: "On m'a pressé pour finir avant le week-end, le code n'est pas parfait.", category: "management" },
  { text: "La démo a été faite sur un jeu de données tronqué.", category: "management" },
  { text: "Le délai était trop court pour inclure la gestion des erreurs.", category: "management" },
  { text: "Le Product Owner a validé la fonctionnalité lors de la revue de sprint.", category: "management" },
  { text: "Les utilisateurs finaux ne font jamais ce genre de manipulation.", category: "management" },
  { text: "Le contenu fourni par l'équipe marketing dépasse la taille des blocs.", category: "management" },
  { text: "C'est une fonctionnalité de la phase 2, on est seulement en phase 1.", category: "management" },
  { text: "Le changement d'architecture a été décidé sans m'en informer.", category: "management" },

  // ==========================================
  // 8. L'ÈRE DE L'IA & GENERATION DE CODE (320-370)
  // ==========================================
  { text: "L'IA de complétion de code m'a induit en erreur.", category: "ai" },
  { text: "Copilot a généré une fonction obsolète et je ne l'ai pas relue.", category: "ai" },
  { text: "Le modèle de langage a halluciné une méthode qui n'existe pas.", category: "ai" },
  { text: "L'invite (prompt) de départ manquait de contexte technique.", category: "ai" },
  { text: "Le code généré par l'IA passait tous les tests locaux.", category: "ai" },
  { text: "Les serveurs d'IA étaient surchargés, j'ai dû écrire le code à la main.", category: "ai" },
  { text: "L'IA a utilisé une structure algorithmique trop complexe pour notre projet.", category: "ai" },
  { text: "Le contexte de la discussion avec l'assistant s'est réinitialisé au milieu.", category: "ai" },
  { text: "Le code d'exemple de la documentation de l'IA était truffé d'erreurs.", category: "ai" },
  { text: "Le générateur automatique a oublié d'importer le module de sécurité.", category: "ai" },
  { text: "J'ai appliqué le correctif suggéré par l'IA sans comprendre l'effet de bord.", category: "ai" },
  { text: "Le filtre de sécurité de l'IA a bloqué le morceau de code dont j'avais besoin.", category: "ai" },
  { text: "L'IA a confondu la syntaxe de deux frameworks différents.", category: "ai" },
  { text: "Le code semblait propre mais la logique interne était inversée.", category: "ai" },
  { text: "J'ai fait confiance aux commentaires générés automatiquement.", category: "ai" },
  { text: "L'IA a écrit une fonction récursive sans condition de sortie.", category: "ai" },
  { text: "La mise à jour du modèle d'IA a changé sa manière de structurer le code.", category: "ai" },
  { text: "Le bot de révision de code (Code Review Bot) a validé le bug.", category: "ai" },
  { text: "L'algorithme de génération a halluciné une faille de sécurité imaginaire.", category: "ai" },
  { text: "Le copier-coller du prompt a inclus des caractères invisibles.", category: "ai" },

  // ==========================================
  // 9. PHYSIQUE, RESEAU & HARDWARE (370-420)
  // ==========================================
  { text: "La connexion Wi-Fi du bureau a sauté pendant le déploiement.", category: "hardware" },
  { text: "Le processeur de ma machine surchauffe et bride les performances.", category: "hardware" },
  { text: "Le câble Ethernet de la baie de serveurs a été débranché par erreur.", category: "hardware" },
  { text: "La foudre est tombée sur le centre de données (datacenter).", category: "hardware" },
  { text: "Ma mémoire vive (RAM) est saturée par les onglets du navigateur.", category: "hardware" },
  { text: "Le disque SSD externe s'est déconnecté pendant l'écriture.", category: "hardware" },
  { text: "Le clavier a un problème de faux contact sur la touche Échap.", category: "hardware" },
  { text: "La bande passante réseau est saturée par une autre application.", category: "hardware" },
  { text: "L'alimentation du serveur de secours a lâché.", category: "hardware" },
  { text: "Les ventilateurs font trop de bruit, je n'arrive pas à me concentrer.", category: "hardware" },
  { text: "Le signal GPS est trop faible pour tester la fonctionnalité de suivi.", category: "hardware" },
  { text: "La mise à jour du système d'exploitation de ma machine bloque le terminal.", category: "hardware" },
  { text: "Le routeur applique des règles de pare-feu trop restrictives.", category: "hardware" },
  { text: "La souris n'a plus de batterie, je ne peux pas cliquer au bon endroit.", category: "hardware" },
  { text: "Le deuxième écran est en panne, je n'ai plus de place pour les outils de dev.", category: "hardware" },
  { text: "Le réseau mobile capte mal en sous-sol pour tester l'application.", category: "hardware" },
  { text: "La passerelle par défaut n'est pas configurée sur cette machine.", category: "hardware" },
  { text: "Une coupure de courant générale a corrompu mes fichiers locaux.", category: "hardware" },
  { text: "Le chiffrement matériel du disque ralentit les opérations d'E/S.", category: "hardware" },
  { text: "La carte réseau surchauffe lors des transferts de gros fichiers.", category: "hardware" },

  // ==========================================
  // 10. MAUVAISE FOI PURE & FACTEUR HUMAIN (420-500)
  // ==========================================
  { text: "Je n'étais pas réveillé quand j'ai écrit cette ligne de code.", category: "bad_faith" },
  { text: "Le café était tiède ce matin, mon efficacité s'en est ressentie.", category: "bad_faith" },
  { text: "C'est la faute de mon binôme, il a validé la Pull Request sans regarder.", category: "bad_faith" },
  { text: "Je pensais que quelqu'un d'autre s'occupait de cette partie.", category: "bad_faith" },
  { text: "Ce bug existait déjà avant que j'arrive dans l'entreprise.", category: "bad_faith" },
  { text: "J'ai contracté une dette technique volontaire pour tenir les délais.", category: "bad_faith" },
  { text: "Mon code est parfait, c'est l'utilisateur qui l'utilise mal.", category: "bad_faith" },
  { text: "Je ne peux pas corriger ça sans casser l'intégralité du système.", category: "bad_faith" },
  { text: "C'est une erreur humaine, et l'erreur est humaine.", category: "bad_faith" },
  { text: "Le bug ne se produit que les jours impairs après 18 heures.", category: "bad_faith" },
  { text: "J'ai été interrompu par trois réunions pendant que je codais cette fonction.", category: "bad_faith" },
  { text: "Le code est tellement élégant que le bug en devient artistique.", category: "bad_faith" },
  { text: "J'ai laissé ce bug exprès pour tester la vigilance de l'équipe de QA.", category: "bad_faith" },
  { text: "Je suis développeur, pas magicien.", category: "bad_faith" },
  { text: "Le code fait exactement ce qu'on lui dit de faire, pas ce que tu veux qu'il fasse.", category: "bad_faith" },
  { text: "C'est un problème d'interprétation philosophique de la consigne.", category: "bad_faith" },
  { text: "Je vais enquêter dessus dès que j'aurai fini ma tâche actuelle (dans trois semaines).", category: "bad_faith" },
  { text: "Le bug s'est auto-corrigé lors du dernier redémarrage, ne touchons à rien.", category: "bad_faith" },
  { text: "C'est le comportement standard défini par l'industrie informatique.", category: "bad_faith" },
  { text: "De toute façon, ce projet va bientôt être réécrit de zéro.", category: "bad_faith" },
  { text: "Le code source a été altéré par des rayons cosmiques sur la mémoire non ECC.", category: "bad_faith" },
  { text: "C'est une anomalie temporelle provoquée par le changement d'heure.", category: "bad_faith" },
  { text: "Mon chat a sauté sur le clavier juste avant le commit.", category: "bad_faith" },
  { text: "Je n'ai pas écrit ce code, c'est mon alter-ego de fin de projet.", category: "bad_faith" },
  { text: "La documentation disait que c'était simple, ils ont menti.", category: "bad_faith" },
  { text: "Le bug est mineur par rapport à l'immensité de l'univers.", category: "bad_faith" },
  { text: "Si on corrige ça, le reste du système s'effondre comme un château de cartes.", category: "bad_faith" },
  { text: "J'ai suivi le tutoriel officiel point par point, plaignez-vous à eux.", category: "bad_faith" },
  { text: "Le code fonctionne mentalement, c'est l'ordinateur qui rejette ma logique.", category: "bad_faith" },
  { text: "C'est à cause de la fatigue accumulée lors du dernier hackathon.", category: "bad_faith" },
  { text: "Le bug est inclus dans le prix de la licence gratuite.", category: "bad_faith" },
  { text: "Le problème vient de la chaise située entre le clavier et l'écran.", category: "bad_faith" },
  { text: "J'étais en train de penser à autre chose, le code s'est écrit tout seul.", category: "bad_faith" },
  { text: "C'est un easter egg caché qui s'est activé trop tôt.", category: "bad_faith" },
  { text: "Le système refuse de fonctionner parce qu'il sent ton stress.", category: "bad_faith" },
  { text: "Le code n'est pas cassé, il est juste en phase d'apprentissage.", category: "bad_faith" },
  { text: "C'est une limitation technique due aux lois de la physique moderne.", category: "bad_faith" },
  { text: "Le bug est indépendant de ma volonté et de mes compétences.", category: "bad_faith" },
  { text: "Je l'ai testé à voix haute et ça sonnait très bien.", category: "bad_faith" },
  { text: "Le code souffre du syndrome de la page blanche.", category: "bad_faith" },
  { text: "C'est un problème d'alignement des planètes avec le serveur de prod.", category: "bad_faith" },
  { text: "J'ai délégué cette tâche à mon subconscient, il a dû faire une erreur.", category: "bad_faith" },
  { text: "Le bug disparaîtra dès que l'application passera de mode.", category: "bad_faith" },
  { text: "C'est une erreur poétique pour casser la monotonie de l'interface.", category: "bad_faith" },
  { text: "Le code est trop en avance sur son temps pour être compris par cette machine.", category: "bad_faith" },
  { text: "J'ai appliqué le principe de moindre surprise, mais la surprise est là.", category: "bad_faith" },
  { text: "Le bug est une illusion d'optique provoquée par la couleur de fond.", category: "bad_faith" },
  { text: "J'ai écrit ça un vendredi après-midi, ça compte pas.", category: "bad_faith" },
  { text: "Le code est en grève solidaire avec l'équipe de modération.", category: "bad_faith" },
  { text: "C'est une erreur de traduction entre le binaire et le français.", category: "bad_faith" },
  { text: "Le compilateur a développé une conscience et refuse de m'obéir.", category: "bad_faith" },
  { text: "J'ai optimisé le code pour la vitesse, pas pour la précision.", category: "bad_faith" },
  { text: "Le bug est une composante essentielle de notre identité de marque.", category: "bad_faith" },
  { text: "C'est l'exception qui confirme la règle de la stabilité du système.", category: "bad_faith" },
  { text: "Le code a été écrit sous l'influence d'une trop forte dose de sucre.", category: "bad_faith" },
  { text: "C'est un secret de fabrication bien gardé.", category: "bad_faith" },
  { text: "Le bug est temporaire, comme notre passage sur cette Terre.", category: "bad_faith" },
  { text: "J'attendais qu'on me demande de le corriger pour prouver mon utilité.", category: "bad_faith" },
  { text: "C'est un hommage discret aux premiers bugs de l'histoire de l'informatique.", category: "bad_faith" },
  { text: "Le code fonctionne parfaitement dans un univers parallèle.", category: "bad_faith" },
  { text: "Je refuse de répondre en présence de mon avocat ou de mon CTO.", category: "bad_faith" },
  { text: "Le bug a été introduit pour équilibrer la charge de travail du support.", category: "bad_faith" },
  { text: "C'est une feature demandée par la concurrence pour nous ralentir.", category: "bad_faith" },
  { text: "Le code est parfait, c'est la réalité qui est mal configurée.", category: "bad_faith" },
  { text: "J'ai fait une mise à jour de mon estime de soi, le code suivra plus tard.", category: "bad_faith" },
  { text: "Le bug est une métaphore de la complexité de notre société moderne.", category: "bad_faith" },
  { text: "J'ai codé ça les yeux fermés pour pimenter mon quotidien.", category: "bad_faith" },
  { text: "C'est le destin, on ne peut pas lutter contre le destin du code.", category: "bad_faith" },
  { text: "Le code a été victime d'un tri sélectif un peu trop agressif.", category: "bad_faith" },
  { text: "C'est un problème d'interprétation textuelle du compilateur.", category: "bad_faith" },
  { text: "Le bug s'autodétruira dans les prochaines vingt-quatre heures.", category: "bad_faith" },
  { text: "J'ai confondu le bouton de sauvegarde et le bouton d'autodestruction.", category: "bad_faith" },
  { text: "C'est une erreur de jeunesse du projet, il faut lui laisser le temps.", category: "bad_faith" },
  { text: "Le code est en train de faire sa crise d'adolescence.", category: "bad_faith" },
  { text: "J'ai écrit ce code pour le futur moi, le présent moi ne le comprend pas.", category: "bad_faith" },
  { text: "Le bug est une invitation à la réflexion et au dialogue d'équipe.", category: "bad_faith" },
  { text: "C'est le résultat d'un consensus mou lors de la dernière réunion.", category: "bad_faith" },
  { text: "Le code est lassé de toujours faire la même chose, il innove.", category: "bad_faith" },
  { text: "J'ai mis le bug en production pour voir si les alertes Datadog fonctionnaient.", category: "bad_faith" },
  { text: "Le code est en mode économie d'énergie, certaines fonctions sont désactivées.", category: "bad_faith" },
  { text: "C'est une erreur de parallélisme entre mes deux mains sur le clavier.", category: "bad_faith" }
];

const DEFAULT_BANNED_WORDS = [
  // RACISM
  { word: 'nègre', category: 'racism' },
  { word: 'négresse', category: 'racism' },
  { word: 'nigger', category: 'racism' },
  { word: 'nigga', category: 'racism' },
  { word: 'bamboula', category: 'racism' },
  { word: 'bougnoule', category: 'racism' },
  { word: 'bicot', category: 'racism' },
  { word: 'chinetoc', category: 'racism' },
  { word: 'chinetoque', category: 'racism' },
  { word: 'macaque', category: 'racism' },
  { word: 'chink', category: 'racism' },
  { word: 'gook', category: 'racism' },
  { word: 'coon', category: 'racism' },

  // THREAT
  { word: 'tuer', category: 'threat' },
  { word: 'assassiner', category: 'threat' },
  { word: 'égorger', category: 'threat' },
  { word: 'bombe', category: 'threat' },
  { word: 'terroriste', category: 'threat' },
  { word: 'suicide', category: 'threat' },
  { word: 'pendre', category: 'threat' },
  { word: 'décapiter', category: 'threat' },
  { word: 'fusiller', category: 'threat' },
  { word: 'massacrer', category: 'threat' },
  { word: 'kill', category: 'threat' },
  { word: 'murder', category: 'threat' },
  { word: 'bomb', category: 'threat' },
  { word: 'terrorist', category: 'threat' },
  { word: 'explosif', category: 'threat' },
  { word: 'kamikaze', category: 'threat' },
  { word: 'k4mikaze', category: 'threat' },
  { word: 'kamikaz', category: 'threat' },
  { word: 'k4mikaz', category: 'threat' },
  { word: 'kamikase', category: 'threat' },
  { word: 'k4mikase', category: 'threat' },

  // SEXUAL
  { word: 'bite', category: 'sexual' },
  { word: 'chatte', category: 'sexual' },
  { word: 'salope', category: 'sexual' },
  { word: 'pute', category: 'sexual' },
  { word: 'pouffiasse', category: 'sexual' },
  { word: 'couille', category: 'sexual' },
  { word: 'couilles', category: 'sexual' },
  { word: 'pénis', category: 'sexual' },
  { word: 'penis', category: 'sexual' },
  { word: 'vagin', category: 'sexual' },
  { word: 'clitoris', category: 'sexual' },
  { word: 'sperme', category: 'sexual' },
  { word: 'branler', category: 'sexual' },
  { word: 'branlette', category: 'sexual' },
  { word: 'fellation', category: 'sexual' },
  { word: 'cunnilingus', category: 'sexual' },
  { word: 'sodomie', category: 'sexual' },
  { word: 'porno', category: 'sexual' },
  { word: 'porn', category: 'sexual' },
  { word: 'nude', category: 'sexual' },
  { word: 'nudes', category: 'sexual' },
  { word: 'hentai', category: 'sexual' },
  { word: 'pédophile', category: 'sexual' },
  { word: 'pedophile', category: 'sexual' },
  { word: 'zoophile', category: 'sexual' },
  { word: 'inceste', category: 'sexual' },
  { word: 'dick', category: 'sexual' },
  { word: 'pussy', category: 'sexual' },
  { word: 'whore', category: 'sexual' },
  { word: 'slut', category: 'sexual' },
  { word: 'cock', category: 'sexual' },
  { word: 'cunt', category: 'sexual' },
  { word: 'vagina', category: 'sexual' },
  { word: 'sperm', category: 'sexual' },
  { word: 'masturbate', category: 'sexual' },
  { word: 'blowjob', category: 'sexual' },
  { word: 'goon', category: 'sexual' },
  { word: 'gooner', category: 'sexual' },
  { word: 'gooners', category: 'sexual' },
  { word: 'gooning', category: 'sexual' },
  { word: 'goonette', category: 'sexual' },

  // LGBTPHOBIA
  { word: 'pédé', category: 'lgbtphobia' },
  { word: 'pedé', category: 'lgbtphobia' },
  { word: 'tarlouze', category: 'lgbtphobia' },
  { word: 'tapette', category: 'lgbtphobia' },
  { word: 'goudou', category: 'lgbtphobia' },
  { word: 'gouine', category: 'lgbtphobia' },
  { word: 'faggot', category: 'lgbtphobia' },
  { word: 'tranny', category: 'lgbtphobia' },
  { word: 'homophobe', category: 'lgbtphobia' },
  { word: 'transphobe', category: 'lgbtphobia' },
  { word: 'fag', category: 'lgbtphobia' },
  { word: 'dyke', category: 'lgbtphobia' },

  // HATE
  { word: 'nazi', category: 'hate' },
  { word: 'hitler', category: 'hate' },
  { word: 'swastika', category: 'hate' },
  { word: 'fasciste', category: 'hate' },
  { word: 'fachiste', category: 'hate' },
  { word: 'antisémite', category: 'hate' },
  { word: 'antisemitic', category: 'hate' },
  { word: 'croix gammée', category: 'hate' },
  { word: 'ku klux klan', category: 'hate' },
  { word: 'kkk', category: 'hate' },
  { word: 'suprématiste', category: 'hate' },
  { word: 'supremacist', category: 'hate' },

  { word: 'supremacist', category: 'hate' },

  // INSULT
  { word: 'con', category: 'insult' },
  { word: 'connard', category: 'insult' },
  { word: 'connasse', category: 'insult' },
  { word: 'salopard', category: 'insult' },
  { word: 'fdp', category: 'insult' },
  { word: 'fils de pute', category: 'insult' },
  { word: 'merde', category: 'insult' },
  { word: 'enculé', category: 'insult' },
  { word: 'encule', category: 'insult' },
  { word: 'abruti', category: 'insult' },
  { word: 'débile', category: 'insult' },
  { word: 'debile', category: 'insult' },
  { word: 'mongol', category: 'insult' },
  { word: 'tocard', category: 'insult' },
  { word: 'crevard', category: 'insult' },
  { word: 'bâtard', category: 'insult' },
  { word: 'batard', category: 'insult' },
  { word: 'gogol', category: 'insult' },
  { word: 'bouffon', category: 'insult' },
  { word: 'asshole', category: 'insult' },
  { word: 'bastard', category: 'insult' },
  { word: 'motherfucker', category: 'insult' },
  { word: 'idiot', category: 'insult' },
  { word: 'retard', category: 'insult' },
  { word: 'dumbass', category: 'insult' },
  { word: 'jerk', category: 'insult' },
  { word: 'piece of shit', category: 'insult' },

  // --- BIG EXPANSION (Français & Anglais, Leetspeak formulations) ---
  // --- RACISM & XENOPHOBIA ---
  { word: 'bougnoul', category: 'racism' },
  { word: 'bougnoules', category: 'racism' },
  { word: 'b0ugnoule', category: 'racism' },
  { word: 'b0ugn0ule', category: 'racism' },
  { word: 'negre', category: 'racism' },
  { word: 'negresse', category: 'racism' },
  { word: 'n1gger', category: 'racism' },
  { word: 'n1gga', category: 'racism' },
  { word: 'niggah', category: 'racism' },
  { word: 'niggas', category: 'racism' },
  { word: 'niggers', category: 'racism' },
  { word: 'ni99er', category: 'racism' },
  { word: 'ni99a', category: 'racism' },
  { word: 'n_i_g_g_e_r', category: 'racism' },
  { word: 'n_i_g_g_a', category: 'racism' },
  { word: 'macaques', category: 'racism' },
  { word: 'macak', category: 'racism' },
  { word: 'macaq', category: 'racism' },
  { word: 'chinetoks', category: 'racism' },
  { word: 'chinetoq', category: 'racism' },
  { word: 'chine-toc', category: 'racism' },
  { word: 'bamboulas', category: 'racism' },
  { word: 'bougni', category: 'racism' },
  { word: 'bicots', category: 'racism' },
  { word: 'chinks', category: 'racism' },
  { word: 'ch1nk', category: 'racism' },
  { word: 'gooks', category: 'racism' },
  { word: 'g00k', category: 'racism' },
  { word: 'coons', category: 'racism' },
  { word: 'c00n', category: 'racism' },
  { word: 'c00ns', category: 'racism' },
  { word: 'kike', category: 'racism' },
  { word: 'kyke', category: 'racism' },
  { word: 'kikes', category: 'racism' },
  { word: 'spic', category: 'racism' },
  { word: 'spick', category: 'racism' },
  { word: 'spics', category: 'racism' },
  { word: 'wog', category: 'racism' },
  { word: 'wogs', category: 'racism' },
  { word: 'wetback', category: 'racism' },
  { word: 'paki', category: 'racism' },
  { word: 'pakis', category: 'racism' },
  { word: 'p4ki', category: 'racism' },
  { word: 'yid', category: 'racism' },
  { word: 'yids', category: 'racism' },
  { word: 'raghead', category: 'racism' },
  { word: 'towelhead', category: 'racism' },
  { word: 'cholo', category: 'racism' },
  { word: 'gringo', category: 'racism' },
  { word: 'gringos', category: 'racism' },
  { word: 'goy', category: 'racism' },
  { word: 'goyim', category: 'racism' },
  { word: 'goyms', category: 'racism' },
  { word: 'negro', category: 'racism' },
  { word: 'negros', category: 'racism' },
  { word: 'negroes', category: 'racism' },
  { word: 'négro', category: 'racism' },
  { word: 'négros', category: 'racism' },
  { word: 'n0irade', category: 'racism' },
  { word: 'noirade', category: 'racism' },
  { word: 'noirades', category: 'racism' },
  { word: 'savage', category: 'racism' },
  { word: 'savages', category: 'racism' },
  { word: 'sauvageon', category: 'racism' },
  { word: 'sauvageons', category: 'racism' },
  { word: 'kaffir', category: 'racism' },
  { word: 'kaffirs', category: 'racism' },
  { word: 'jungle bunny', category: 'racism' },
  { word: 'porc-noir', category: 'racism' },
  { word: 'sale arabe', category: 'racism' },
  { word: 'sale noir', category: 'racism' },
  { word: 'sale blanc', category: 'racism' },
  { word: 'sale juif', category: 'racism' },
  { word: 'sale chinois', category: 'racism' },
  { word: 'dirty jew', category: 'racism' },
  { word: 'dirty arab', category: 'racism' },
  { word: 'dirty black', category: 'racism' },
  { word: 'dirty white', category: 'racism' },

  // --- THREAT & VIOLENCE ---
  { word: 'tueras', category: 'threat' },
  { word: 'tuerai', category: 'threat' },
  { word: 'tuons', category: 'threat' },
  { word: 'tuez', category: 'threat' },
  { word: 'tueront', category: 'threat' },
  { word: 'assassins', category: 'threat' },
  { word: 'assassine', category: 'threat' },
  { word: 'assassinat', category: 'threat' },
  { word: 'assassinats', category: 'threat' },
  { word: 'égorgements', category: 'threat' },
  { word: 'égorge', category: 'threat' },
  { word: 'egorger', category: 'threat' },
  { word: 'egorge', category: 'threat' },
  { word: 'decapiter', category: 'threat' },
  { word: 'décapite', category: 'threat' },
  { word: 'decapite', category: 'threat' },
  { word: 'decapitation', category: 'threat' },
  { word: 'décapitation', category: 'threat' },
  { word: 'bombes', category: 'threat' },
  { word: 'bombardement', category: 'threat' },
  { word: 'b0mbe', category: 'threat' },
  { word: 'b0mbes', category: 'threat' },
  { word: 'explosifs', category: 'threat' },
  { word: 'explosion', category: 'threat' },
  { word: 'c4', category: 'threat' },
  { word: 'semtex', category: 'threat' },
  { word: 'dynamite', category: 'threat' },
  { word: 'attentat', category: 'threat' },
  { word: 'attentats', category: 'threat' },
  { word: 'terrorisme', category: 'threat' },
  { word: 'terroristes', category: 'threat' },
  { word: 'terr0riste', category: 'threat' },
  { word: 'suicides', category: 'threat' },
  { word: 'suicidaire', category: 'threat' },
  { word: 'suicider', category: 'threat' },
  { word: 'pendaison', category: 'threat' },
  { word: 'pendus', category: 'threat' },
  { word: 'pendu', category: 'threat' },
  { word: 'pende', category: 'threat' },
  { word: 'fusillade', category: 'threat' },
  { word: 'fusillades', category: 'threat' },
  { word: 'fusil', category: 'threat' },
  { word: 'massacres', category: 'threat' },
  { word: 'massacrant', category: 'threat' },
  { word: 'assaut', category: 'threat' },
  { word: 'égorgement', category: 'threat' },
  { word: 'throatcut', category: 'threat' },
  { word: 'killing', category: 'threat' },
  { word: 'kills', category: 'threat' },
  { word: 'killer', category: 'threat' },
  { word: 'killers', category: 'threat' },
  { word: 'k1ll', category: 'threat' },
  { word: 'k1ller', category: 'threat' },
  { word: 'k1lling', category: 'threat' },
  { word: 'murders', category: 'threat' },
  { word: 'murderer', category: 'threat' },
  { word: 'murderers', category: 'threat' },
  { word: 'murd3r', category: 'threat' },
  { word: 'bombs', category: 'threat' },
  { word: 'bomber', category: 'threat' },
  { word: 'bombers', category: 'threat' },
  { word: 'bombing', category: 'threat' },
  { word: 'b0mb', category: 'threat' },
  { word: 'b0mbs', category: 'threat' },
  { word: 'terrorists', category: 'threat' },
  { word: 'terrorism', category: 'threat' },
  { word: 'terr0rist', category: 'threat' },
  { word: 'genocide', category: 'threat' },
  { word: 'génocide', category: 'threat' },
  { word: 'genocides', category: 'threat' },
  { word: 'génocides', category: 'threat' },
  { word: 'poison', category: 'threat' },
  { word: 'poisoning', category: 'threat' },
  { word: 'poisoned', category: 'threat' },
  { word: 'empoisonner', category: 'threat' },
  { word: 'fusille', category: 'threat' },
  { word: 'kalach', category: 'threat' },
  { word: 'kalachnikov', category: 'threat' },
  { word: 'ak47', category: 'threat' },
  { word: 'ar15', category: 'threat' },
  { word: 'fusil-mitrailleur', category: 'threat' },
  { word: 'guerre', category: 'threat' },
  { word: 'djihad', category: 'threat' },
  { word: 'jihad', category: 'threat' },
  { word: 'djihadiste', category: 'threat' },
  { word: 'jihadist', category: 'threat' },
  { word: 'djihadistes', category: 'threat' },
  { word: 'jihadists', category: 'threat' },
  { word: 'calife', category: 'threat' },
  { word: 'califat', category: 'threat' },
  { word: 'caliphate', category: 'threat' },
  { word: 'daesh', category: 'threat' },
  { word: 'isis', category: 'threat' },
  { word: 'al-qaida', category: 'threat' },
  { word: 'alqaida', category: 'threat' },
  { word: 'al-qaïda', category: 'threat' },
  { word: 'taliban', category: 'threat' },
  { word: 'talibans', category: 'threat' },
  { word: 'boko haram', category: 'threat' },
  { word: 'bokoharam', category: 'threat' },
  { word: 'suicide bomb', category: 'threat' },
  { word: 'suicide bomber', category: 'threat' },
  { word: 'school shooting', category: 'threat' },
  { word: 'school shooter', category: 'threat' },
  { word: 'columbine', category: 'threat' },
  { word: 'hate speech', category: 'threat' },
  { word: 'threaten', category: 'threat' },
  { word: 'threatening', category: 'threat' },
  { word: 'threats', category: 'threat' },
  { word: 'menace', category: 'threat' },
  { word: 'menaces', category: 'threat' },
  { word: 'menacer', category: 'threat' },
  { word: 'm4nikaze', category: 'threat' },
  { word: 'kamikazes', category: 'threat' },
  { word: 'k4mikazes', category: 'threat' },
  { word: 'kamikases', category: 'threat' },
  { word: 'k4mikases', category: 'threat' },
  { word: 'kamikazs', category: 'threat' },
  { word: 'k4mikazs', category: 'threat' },

  // --- SEXUAL & PORNOGRAPHIC ---
  { word: 'bites', category: 'sexual' },
  { word: 'b1te', category: 'sexual' },
  { word: 'b1tes', category: 'sexual' },
  { word: 'chattes', category: 'sexual' },
  { word: 'shatte', category: 'sexual' },
  { word: 'shattes', category: 'sexual' },
  { word: 'salopes', category: 'sexual' },
  { word: 's4lope', category: 'sexual' },
  { word: 's4lopes', category: 'sexual' },
  { word: 'putes', category: 'sexual' },
  { word: 'p_u_t_e', category: 'sexual' },
  { word: 'p1te', category: 'sexual' },
  { word: 'p1tes', category: 'sexual' },
  { word: 'putain', category: 'sexual' },
  { word: 'putains', category: 'sexual' },
  { word: 'pouffiasses', category: 'sexual' },
  { word: 'couillere', category: 'sexual' },
  { word: 'c0uille', category: 'sexual' },
  { word: 'c0uilles', category: 'sexual' },
  { word: 'péniss', category: 'sexual' },
  { word: 'peniss', category: 'sexual' },
  { word: 'p3nis', category: 'sexual' },
  { word: 'vagins', category: 'sexual' },
  { word: 'v4gin', category: 'sexual' },
  { word: 'v4gins', category: 'sexual' },
  { word: 'clito', category: 'sexual' },
  { word: 'clitos', category: 'sexual' },
  { word: 'clit0ris', category: 'sexual' },
  { word: 'spermes', category: 'sexual' },
  { word: 'cum', category: 'sexual' },
  { word: 'cumshot', category: 'sexual' },
  { word: 'cumshots', category: 'sexual' },
  { word: 'cuming', category: 'sexual' },
  { word: 'orgasme', category: 'sexual' },
  { word: 'orgasmes', category: 'sexual' },
  { word: 'orgasm', category: 'sexual' },
  { word: 'orgasms', category: 'sexual' },
  { word: 'ejaculation', category: 'sexual' },
  { word: 'éjaculation', category: 'sexual' },
  { word: 'ejaculer', category: 'sexual' },
  { word: 'éjaculer', category: 'sexual' },
  { word: 'masturbation', category: 'sexual' },
  { word: 'masturber', category: 'sexual' },
  { word: 'masturbes', category: 'sexual' },
  { word: 'branlette espagnole', category: 'sexual' },
  { word: 'fellations', category: 'sexual' },
  { word: 'cunnilinguss', category: 'sexual' },
  { word: 'deepthroat', category: 'sexual' },
  { word: 'sodomies', category: 'sexual' },
  { word: 'sodomiser', category: 'sexual' },
  { word: 'sodomise', category: 'sexual' },
  { word: 'sodomized', category: 'sexual' },
  { word: 'sodomize', category: 'sexual' },
  { word: 'enculade', category: 'sexual' },
  { word: 'pornos', category: 'sexual' },
  { word: 'pornographie', category: 'sexual' },
  { word: 'pornography', category: 'sexual' },
  { word: 'p0rno', category: 'sexual' },
  { word: 'p0rn', category: 'sexual' },
  { word: 'p0rnography', category: 'sexual' },
  { word: 'hentais', category: 'sexual' },
  { word: 'h3ntai', category: 'sexual' },
  { word: 'ecchi', category: 'sexual' },
  { word: 'nsfw', category: 'sexual' },
  { word: 'pedophiles', category: 'sexual' },
  { word: 'pédophiles', category: 'sexual' },
  { word: 'pédophilie', category: 'sexual' },
  { word: 'pedophilia', category: 'sexual' },
  { word: 'ped0phile', category: 'sexual' },
  { word: 'zoophiles', category: 'sexual' },
  { word: 'zoophilia', category: 'sexual' },
  { word: 'bestiality', category: 'sexual' },
  { word: 'incestes', category: 'sexual' },
  { word: 'incestuous', category: 'sexual' },
  { word: 'incest', category: 'sexual' },
  { word: 'dicks', category: 'sexual' },
  { word: 'd1ck', category: 'sexual' },
  { word: 'd1cks', category: 'sexual' },
  { word: 'pussies', category: 'sexual' },
  { word: 'pussys', category: 'sexual' },
  { word: 'puss1e', category: 'sexual' },
  { word: 'whores', category: 'sexual' },
  { word: 'wh0re', category: 'sexual' },
  { word: 'wh0res', category: 'sexual' },
  { word: 'sluts', category: 'sexual' },
  { word: 'sl_ut', category: 'sexual' },
  { word: 'slutty', category: 'sexual' },
  { word: 'cocks', category: 'sexual' },
  { word: 'c0ck', category: 'sexual' },
  { word: 'c0cks', category: 'sexual' },
  { word: 'cunts', category: 'sexual' },
  { word: 'c_u_n_t', category: 'sexual' },
  { word: 'vaginas', category: 'sexual' },
  { word: 'v4gina', category: 'sexual' },
  { word: 'sperms', category: 'sexual' },
  { word: 'masturbating', category: 'sexual' },
  { word: 'blowjobs', category: 'sexual' },
  { word: 'bl0wjob', category: 'sexual' },
  { word: 'handjob', category: 'sexual' },
  { word: 'handjobs', category: 'sexual' },
  { word: 'gangbang', category: 'sexual' },
  { word: 'gangbangs', category: 'sexual' },
  { word: 'threesome', category: 'sexual' },
  { word: 'threesomes', category: 'sexual' },
  { word: 'orgy', category: 'sexual' },
  { word: 'orgies', category: 'sexual' },
  { word: 'milf', category: 'sexual' },
  { word: 'milfs', category: 'sexual' },
  { word: 'dilf', category: 'sexual' },
  { word: 'dilfs', category: 'sexual' },
  { word: 'bastardize', category: 'sexual' },
  { word: 'hardcore', category: 'sexual' },
  { word: 'erotic', category: 'sexual' },
  { word: 'erotica', category: 'sexual' },
  { word: 'érotique', category: 'sexual' },
  { word: 'swinger', category: 'sexual' },
  { word: 'swingers', category: 'sexual' },
  { word: 'sex', category: 'sexual' },
  { word: 'sexe', category: 'sexual' },
  { word: 'sexes', category: 'sexual' },
  { word: 'sexy', category: 'sexual' },
  { word: 'sexualise', category: 'sexual' },
  { word: 'sexualised', category: 'sexual' },
  { word: 'sexualiser', category: 'sexual' },
  { word: 'violer', category: 'sexual' },
  { word: 'violé', category: 'sexual' },
  { word: 'violée', category: 'sexual' },
  { word: 'violés', category: 'sexual' },
  { word: 'viols', category: 'sexual' },
  { word: 'viol', category: 'sexual' },
  { word: 'rape', category: 'sexual' },
  { word: 'raped', category: 'sexual' },
  { word: 'raping', category: 'sexual' },
  { word: 'rapist', category: 'sexual' },
  { word: 'rapists', category: 'sexual' },
  { word: 'r4pe', category: 'sexual' },
  { word: 'agression sexuelle', category: 'sexual' },
  { word: 'agressions sexuelles', category: 'sexual' },
  { word: 'harcèlement sexuel', category: 'sexual' },
  { word: 'sexual harassment', category: 'sexual' },
  { word: 'sexual assault', category: 'sexual' },
  { word: 'sexual assaults', category: 'sexual' },
  { word: 'voyeur', category: 'sexual' },
  { word: 'voyeurs', category: 'sexual' },
  { word: 'fetish', category: 'sexual' },
  { word: 'fétichisme', category: 'sexual' },
  { word: 'fétiche', category: 'sexual' },
  { word: 'bds m', category: 'sexual' },
  { word: 'bdsm', category: 'sexual' },
  { word: 'bondage', category: 'sexual' },
  { word: 'sadomasochisme', category: 'sexual' },
  { word: 'sadomasochism', category: 'sexual' },
  { word: 'escort', category: 'sexual' },
  { word: 'escorte', category: 'sexual' },
  { word: 'escorts', category: 'sexual' },
  { word: 'prostituée', category: 'sexual' },
  { word: 'prostitué', category: 'sexual' },
  { word: 'prostitutes', category: 'sexual' },
  { word: 'prostitute', category: 'sexual' },
  { word: 'prostitution', category: 'sexual' },
  { word: 'gigolo', category: 'sexual' },
  { word: 'gigolos', category: 'sexual' },
  { word: 'michto', category: 'sexual' },
  { word: 'michtonneuse', category: 'sexual' },
  { word: 'michtonneuses', category: 'sexual' },
  { word: 'baisodrome', category: 'sexual' },
  { word: 'tringler', category: 'sexual' },
  { word: 'tringlé', category: 'sexual' },
  { word: 'niquer', category: 'sexual' },
  { word: 'nique', category: 'sexual' },
  { word: 'niqué', category: 'sexual' },
  { word: 'niques', category: 'sexual' },
  { word: 'n1quer', category: 'sexual' },
  { word: 'baiser', category: 'sexual' },
  { word: 'baise', category: 'sexual' },
  { word: 'baisé', category: 'sexual' },
  { word: 'baisent', category: 'sexual' },
  { word: 'baisou', category: 'sexual' },
  { word: 'foutre', category: 'sexual' },
  { word: 'foutu', category: 'sexual' },
  { word: 'foutue', category: 'sexual' },
  { word: 'foutre-dieu', category: 'sexual' },
  { word: 'juter', category: 'sexual' },
  { word: 'jute', category: 'sexual' },
  { word: 'juteux', category: 'sexual' },
  { word: 'juteuse', category: 'sexual' },
  { word: 'boule', category: 'sexual' },
  { word: 'boules', category: 'sexual' },
  { word: 'fesses', category: 'sexual' },
  { word: 'fesse', category: 'sexual' },
  { word: 'cul', category: 'sexual' },
  { word: 'culs', category: 'sexual' },
  { word: 'ass', category: 'sexual' },
  { word: 'asses', category: 'sexual' },
  { word: 'butt', category: 'sexual' },
  { word: 'butts', category: 'sexual' },
  { word: 'booty', category: 'sexual' },
  { word: 'booties', category: 'sexual' },
  { word: 'boobs', category: 'sexual' },
  { word: 'boob', category: 'sexual' },
  { word: 'tits', category: 'sexual' },
  { word: 'tit', category: 'sexual' },
  { word: 'teton', category: 'sexual' },
  { word: 'téton', category: 'sexual' },
  { word: 'tetons', category: 'sexual' },
  { word: 'tétons', category: 'sexual' },
  { word: 'nipple', category: 'sexual' },
  { word: 'nipples', category: 'sexual' },
  { word: 'titsout', category: 'sexual' },
  { word: 'topless', category: 'sexual' },
  { word: 'sans-haut', category: 'sexual' },

  // --- LGBTPHOBIA ---
  { word: 'pédés', category: 'lgbtphobia' },
  { word: 'pedés', category: 'lgbtphobia' },
  { word: 'p3de', category: 'lgbtphobia' },
  { word: 'p3dés', category: 'lgbtphobia' },
  { word: 'p-é-d-é', category: 'lgbtphobia' },
  { word: 'tarlouzes', category: 'lgbtphobia' },
  { word: 'tapettes', category: 'lgbtphobia' },
  { word: 'tapette-cul', category: 'lgbtphobia' },
  { word: 't4pette', category: 'lgbtphobia' },
  { word: 'goudous', category: 'lgbtphobia' },
  { word: 'gouines', category: 'lgbtphobia' },
  { word: 'g0uine', category: 'lgbtphobia' },
  { word: 'faggots', category: 'lgbtphobia' },
  { word: 'fagots', category: 'lgbtphobia' },
  { word: 'fag0t', category: 'lgbtphobia' },
  { word: 'fag0ts', category: 'lgbtphobia' },
  { word: 'f4g', category: 'lgbtphobia' },
  { word: 'f4gs', category: 'lgbtphobia' },
  { word: 'fags', category: 'lgbtphobia' },
  { word: 'dykes', category: 'lgbtphobia' },
  { word: 'd0yke', category: 'lgbtphobia' },
  { word: 'homophobes', category: 'lgbtphobia' },
  { word: 'homophobia', category: 'lgbtphobia' },
  { word: 'transphobes', category: 'lgbtphobia' },
  { word: 'transphobia', category: 'lgbtphobia' },
  { word: 'trannys', category: 'lgbtphobia' },
  { word: 'trannie', category: 'lgbtphobia' },
  { word: 'trannies', category: 'lgbtphobia' },
  { word: 'lesbophobe', category: 'lgbtphobia' },
  { word: 'lesbophobia', category: 'lgbtphobia' },
  { word: 'lesbophobie', category: 'lgbtphobia' },
  { word: 'biphobe', category: 'lgbtphobia' },
  { word: 'biphobie', category: 'lgbtphobia' },
  { word: 'biphobia', category: 'lgbtphobia' },
  { word: 'lgbtphobes', category: 'lgbtphobia' },
  { word: 'lgbtphobie', category: 'lgbtphobia' },
  { word: 'queerbaiting', category: 'lgbtphobia' },
  { word: 'shemale', category: 'lgbtphobia' },
  { word: 'shemales', category: 'lgbtphobia' },
  { word: 'ladyboy', category: 'lgbtphobia' },
  { word: 'ladyboys', category: 'lgbtphobia' },
  { word: 'garlouze', category: 'lgbtphobia' },
  { word: 'enculeur de mouches', category: 'lgbtphobia' },
  { word: 'pd', category: 'lgbtphobia' },
  { word: 'pds', category: 'lgbtphobia' },
  { word: 'queer-trash', category: 'lgbtphobia' },

  // --- HATE & FASCISM ---
  { word: 'nazis', category: 'hate' },
  { word: 'n4zi', category: 'hate' },
  { word: 'n4zis', category: 'hate' },
  { word: 'neo-nazi', category: 'hate' },
  { word: 'neonazi', category: 'hate' },
  { word: 'neo-nazis', category: 'hate' },
  { word: 'neonazis', category: 'hate' },
  { word: 'adolf', category: 'hate' },
  { word: 'adolf hitler', category: 'hate' },
  { word: 'swastikas', category: 'hate' },
  { word: 'fascistes', category: 'hate' },
  { word: 'fascism', category: 'hate' },
  { word: 'fascisme', category: 'hate' },
  { word: 'facho', category: 'hate' },
  { word: 'fachos', category: 'hate' },
  { word: 'fachisme', category: 'hate' },
  { word: 'fachistes', category: 'hate' },
  { word: 'antisemite', category: 'hate' },
  { word: 'antisemites', category: 'hate' },
  { word: 'antisémites', category: 'hate' },
  { word: 'antisemitisme', category: 'hate' },
  { word: 'antisémitisme', category: 'hate' },
  { word: 'antisemitism', category: 'hate' },
  { word: 'croix gammee', category: 'hate' },
  { word: 'croix-gammee', category: 'hate' },
  { word: 'croix-gammée', category: 'hate' },
  { word: 'mein kampf', category: 'hate' },
  { word: 'ku-klux-klan', category: 'hate' },
  { word: 'kukluxklan', category: 'hate' },
  { word: 'suprématistes', category: 'hate' },
  { word: 'suprématie', category: 'hate' },
  { word: 'supremacy', category: 'hate' },
  { word: 'white supremacy', category: 'hate' },
  { word: 'white supremacist', category: 'hate' },
  { word: 'white supremacists', category: 'hate' },
  { word: 'suprémaciste blanc', category: 'hate' },
  { word: 'suprémacistes blancs', category: 'hate' },
  { word: 'black power', category: 'hate' },
  { word: 'holocauste', category: 'hate' },
  { word: 'holocaust', category: 'hate' },
  { word: 'shoah', category: 'hate' },
  { word: 'revisionniste', category: 'hate' },
  { word: 'révisionniste', category: 'hate' },
  { word: 'revisionnistes', category: 'hate' },
  { word: 'révisionnistes', category: 'hate' },
  { word: 'revisionism', category: 'hate' },
  { word: 'negationniste', category: 'hate' },
  { word: 'négationniste', category: 'hate' },
  { word: 'negationnistes', category: 'hate' },
  { word: 'négationnistes', category: 'hate' },
  { word: 'negationnisme', category: 'hate' },
  { word: 'négationnisme', category: 'hate' },
  { word: 'genocidaire', category: 'hate' },
  { word: 'génocidaire', category: 'hate' },
  { word: 'genocidaires', category: 'hate' },
  { word: 'génocidaires', category: 'hate' },
  { word: 'gestapo', category: 'hate' },
  { word: 'ss-officer', category: 'hate' },
  { word: 'waffen-ss', category: 'hate' },
  { word: 'waffenss', category: 'hate' },
  { word: 'aryen', category: 'hate' },
  { word: 'aryens', category: 'hate' },
  { word: 'aryan', category: 'hate' },
  { word: 'aryans', category: 'hate' },
  { word: 'fascio', category: 'hate' },
  { word: 'mussolini', category: 'hate' },
  { word: 'salazar', category: 'hate' },
  { word: 'francoism', category: 'hate' },
  { word: 'francoiste', category: 'hate' },
  { word: 'petain', category: 'hate' },
  { word: 'pétain', category: 'hate' },
  { word: 'petainiste', category: 'hate' },
  { word: 'pétainiste', category: 'hate' },
  { word: 'petainistes', category: 'hate' },
  { word: 'pétainistes', category: 'hate' },
  { word: 'collaborateur', category: 'hate' },
  { word: 'collabo', category: 'hate' },
  { word: 'collabos', category: 'hate' },
  { word: 'collaborateurs', category: 'hate' },
  { word: 'vichy regime', category: 'hate' },
  { word: 'regime de vichy', category: 'hate' },
  { word: 'régime de vichy', category: 'hate' },

  // --- GENERAL INSULTS & OBSCENITIES ---
  { word: 'cons', category: 'insult' },
  { word: 'connards', category: 'insult' },
  { word: 'c0nnard', category: 'insult' },
  { word: 'c0nnards', category: 'insult' },
  { word: 'connasses', category: 'insult' },
  { word: 'c0nnasse', category: 'insult' },
  { word: 'salopards', category: 'insult' },
  { word: 's4lopard', category: 'insult' },
  { word: 's4lopards', category: 'insult' },
  { word: 'fdps', category: 'insult' },
  { word: 'f.d.p', category: 'insult' },
  { word: 'f_d_p', category: 'insult' },
  { word: 'fils de putes', category: 'insult' },
  { word: 'merdes', category: 'insult' },
  { word: 'merdeux', category: 'insult' },
  { word: 'merdeuse', category: 'insult' },
  { word: 'm3rde', category: 'insult' },
  { word: 'enculés', category: 'insult' },
  { word: 'encules', category: 'insult' },
  { word: 'enculées', category: 'insult' },
  { word: 'enculees', category: 'insult' },
  { word: '3nculé', category: 'insult' },
  { word: '3ncule', category: 'insult' },
  { word: 'abrutis', category: 'insult' },
  { word: 'abrutie', category: 'insult' },
  { word: 'abruties', category: 'insult' },
  { word: 'débiles', category: 'insult' },
  { word: 'debiles', category: 'insult' },
  { word: 'd3bile', category: 'insult' },
  { word: 'd3biles', category: 'insult' },
  { word: 'mongols', category: 'insult' },
  { word: 'mongoliens', category: 'insult' },
  { word: 'mongolienne', category: 'insult' },
  { word: 'mongoliennes', category: 'insult' },
  { word: 'm0ngol', category: 'insult' },
  { word: 'tocards', category: 'insult' },
  { word: 'tocarde', category: 'insult' },
  { word: 'tocardes', category: 'insult' },
  { word: 'crevards', category: 'insult' },
  { word: 'crevarda', category: 'insult' },
  { word: 'crevarde', category: 'insult' },
  { word: 'bâtards', category: 'insult' },
  { word: 'batards', category: 'insult' },
  { word: 'bâtarde', category: 'insult' },
  { word: 'batarde', category: 'insult' },
  { word: 'b4tard', category: 'insult' },
  { word: 'gogols', category: 'insult' },
  { word: 'g0g0l', category: 'insult' },
  { word: 'g0g0ls', category: 'insult' },
  { word: 'bouffons', category: 'insult' },
  { word: 'bouffonne', category: 'insult' },
  { word: 'bouffonnes', category: 'insult' },
  { word: 'assholes', category: 'insult' },
  { word: '4sshole', category: 'insult' },
  { word: '4ssholes', category: 'insult' },
  { word: 'bastards', category: 'insult' },
  { word: 'b4stard', category: 'insult' },
  { word: 'motherfuckers', category: 'insult' },
  { word: 'm0therfucker', category: 'insult' },
  { word: 'm0therfuckers', category: 'insult' },
  { word: 'muthafucka', category: 'insult' },
  { word: 'muthafuckas', category: 'insult' },
  { word: 'idiots', category: 'insult' },
  { word: 'idiote', category: 'insult' },
  { word: 'idiotes', category: 'insult' },
  { word: '1diot', category: 'insult' },
  { word: '1diots', category: 'insult' },
  { word: 'retards', category: 'insult' },
  { word: 'retarded', category: 'insult' },
  { word: 'r3tard', category: 'insult' },
  { word: 'r3tards', category: 'insult' },
  { word: 'dumbasses', category: 'insult' },
  { word: 'dumb', category: 'insult' },
  { word: 'jerks', category: 'insult' },
  { word: 'j3rk', category: 'insult' },
  { word: 'pieces of shit', category: 'insult' },
  { word: 'crap', category: 'insult' },
  { word: 'crappy', category: 'insult' },
  { word: 'shit', category: 'insult' },
  { word: 'shits', category: 'insult' },
  { word: 'shitty', category: 'insult' },
  { word: 'sh1t', category: 'insult' },
  { word: 'fuck', category: 'insult' },
  { word: 'fucks', category: 'insult' },
  { word: 'fucking', category: 'insult' },
  { word: 'fucked', category: 'insult' },
  { word: 'fucker', category: 'insult' },
  { word: 'fuckers', category: 'insult' },
  { word: 'f_u_c_k', category: 'insult' },
  { word: 'f*ck', category: 'insult' },
  { word: 'f**k', category: 'insult' },
  { word: 'bitch', category: 'insult' },
  { word: 'bitches', category: 'insult' },
  { word: 'b1tch', category: 'insult' },
  { word: 'b1tches', category: 'insult' },
  { word: 'son of a bitch', category: 'insult' },
  { word: 'son of a b1tch', category: 'insult' },
  { word: 'sons of bitches', category: 'insult' },
  { word: 'crapula', category: 'insult' },
  { word: 'crapule', category: 'insult' },
  { word: 'crapules', category: 'insult' },
  { word: 'ordure', category: 'insult' },
  { word: 'ordures', category: 'insult' },
  { word: 'racaille', category: 'insult' },
  { word: 'racailles', category: 'insult' },
  { word: 'voyou', category: 'insult' },
  { word: 'voyous', category: 'insult' },
  { word: 'pourceau', category: 'insult' },
  { word: 'pourceaux', category: 'insult' },
  { word: 'pourceau-dieu', category: 'insult' },
  { word: 'porc', category: 'insult' },
  { word: 'porcs', category: 'insult' },
  { word: 'chienne', category: 'insult' },
  { word: 'chiennes', category: 'insult' },
  { word: 'salop', category: 'insult' },
  { word: 'salops', category: 'insult' },
  { word: 'cretin', category: 'insult' },
  { word: 'crétin', category: 'insult' },
  { word: 'cretins', category: 'insult' },
  { word: 'crétins', category: 'insult' },
  { word: 'cretine', category: 'insult' },
  { word: 'crétine', category: 'insult' },
  { word: 'stupide', category: 'insult' },
  { word: 'stupides', category: 'insult' },
  { word: 'imbecile', category: 'insult' },
  { word: 'imbécile', category: 'insult' },
  { word: 'imbeciles', category: 'insult' },
  { word: 'imbéciles', category: 'insult' },
  { word: 'ignare', category: 'insult' },
  { word: 'ignares', category: 'insult' },
  { word: 'va te faire', category: 'insult' },
  { word: 'va te faire foutre', category: 'insult' },
  { word: 'va t faire foutre', category: 'insult' },
  { word: 'mange tes morts', category: 'insult' },
  { word: 'mange tes m0rts', category: 'insult' },
  { word: 'casse toi', category: 'insult' },
  { word: 'casse-toi', category: 'insult' },
  { word: 'degage', category: 'insult' },
  { word: 'dégage', category: 'insult' },
  { word: 'nique ta mere', category: 'insult' },
  { word: 'nique ta méré', category: 'insult' },
  { word: 'nique ta m3re', category: 'insult' },
  { word: 'nique ta race', category: 'insult' },
  { word: 'nique ta r4ce', category: 'insult' },
  { word: 'nique ton pere', category: 'insult' },
  { word: 'nique ton p3re', category: 'insult' },
  { word: 'baise ta mere', category: 'insult' },
  { word: 'baise ta m3re', category: 'insult' },
  { word: 'chier', category: 'insult' },
  { word: 'chie', category: 'insult' },
  { word: 'chieur', category: 'insult' },
  { word: 'chieuse', category: 'insult' },
  { word: 'chieurs', category: 'insult' },
  { word: 'chiant', category: 'insult' },
  { word: 'chiante', category: 'insult' },
  { word: 'fait chier', category: 'insult' },
  { word: 'fout la merde', category: 'insult' },
  { word: 'fouteur de merde', category: 'insult' },
  { word: 'fouteuse de merde', category: 'insult' },
  { word: 'fouteurs de merde', category: 'insult' },
  { word: 'trou du cul', category: 'insult' },
  { word: 'trouduc', category: 'insult' },
  { word: 'trou d cul', category: 'insult' },
  { word: 'trou-du-cul', category: 'insult' },
  { word: 'trous du cul', category: 'insult' },
  { word: 'ass wipe', category: 'insult' },
  { word: 'asswipe', category: 'insult' },
  { word: 'butt wipe', category: 'insult' },
  { word: 'douchebag', category: 'insult' },
  { word: 'douchebags', category: 'insult' },
  { word: 'scumbag', category: 'insult' },
  { word: 'scumbags', category: 'insult' },
  { word: 'sucker', category: 'insult' },
  { word: 'suckers', category: 'insult' },
  { word: 'suck my dick', category: 'insult' },
  { word: 'suck my cock', category: 'insult' },
  { word: 'suce ma bite', category: 'insult' },
  { word: 'suce ma b1te', category: 'insult' },
  { word: 'suce mon penis', category: 'insult' },
  { word: 'suce mon pénis', category: 'insult' },
  { word: 'va sucer', category: 'insult' },
  { word: 'pisse', category: 'insult' },
  { word: 'pisser', category: 'insult' },
  { word: 'pisseur', category: 'insult' },
  { word: 'pisseux', category: 'insult' },
  { word: 'pisseuse', category: 'insult' },
  { word: 'cuntbag', category: 'insult' },
  { word: 'clitbag', category: 'insult' },
  { word: 'wanker', category: 'insult' },
  { word: 'wankers', category: 'insult' },
  { word: 'twat', category: 'insult' },
  { word: 'twats', category: 'insult' },
  { word: 'tosser', category: 'insult' },
  { word: 'tossers', category: 'insult' },
  { word: 'bellend', category: 'insult' },
  { word: 'bellends', category: 'insult' },
  { word: 'bollocks', category: 'insult' },
  { word: 'bollock', category: 'insult' },
  { word: 'prick', category: 'insult' },
  { word: 'pricks', category: 'insult' },
  { word: 'plonker', category: 'insult' },
  { word: 'plonkers', category: 'insult' },
  { word: 'muppet', category: 'insult' },
  { word: 'muppets', category: 'insult' },
  { word: 'dipshit', category: 'insult' },
  { word: 'dipshits', category: 'insult' },
  { word: 'jackass', category: 'insult' },
  { word: 'jackasses', category: 'insult' },
  { word: 'bloody hell', category: 'insult' },
  { word: 'craphead', category: 'insult' },
  { word: 'shithead', category: 'insult' },
  { word: 'shitheads', category: 'insult' },
  { word: 'dickhead', category: 'insult' },
  { word: 'dickheads', category: 'insult' },
  { word: 'pussy whipping', category: 'insult' },
  { word: 'pussywhipped', category: 'insult' },
  { word: 'badtripper', category: 'insult' },
  { word: 'chieur-né', category: 'insult' },
  { word: 'brise-burnes', category: 'insult' },
  { word: 'casse-couilles', category: 'insult' },
  { word: 'casse-couille', category: 'insult' },
  { word: 'casse-bonbons', category: 'insult' },
  { word: 'casse-burnes', category: 'insult' },
  { word: 'casse couilles', category: 'insult' },
  { word: 'casse couille', category: 'insult' },
  { word: 'broute-minou', category: 'insult' },
  { word: 'broute minou', category: 'insult' },
  { word: 'leche-cul', category: 'insult' },
  { word: 'lèche-cul', category: 'insult' },
  { word: 'lèche cul', category: 'insult' },
  { word: 'leche cul', category: 'insult' },
  { word: 'leche-botte', category: 'insult' },
  { word: 'lèche-botte', category: 'insult' },
  { word: 'lèche-bottes', category: 'insult' },
  { word: 'leche-bottes', category: 'insult' },
  { word: 'larbin', category: 'insult' },
  { word: 'larbins', category: 'insult' },
  { word: 'collabo-trash', category: 'insult' },
  { word: 'lechecul', category: 'insult' },
  { word: 'lechebottes', category: 'insult' },
  { word: 'suce-boules', category: 'insult' },
  { word: 'suce boules', category: 'insult' },
  { word: 'suce-boule', category: 'insult' },
  { word: 'suce boule', category: 'insult' },
  { word: 'suceboule', category: 'insult' },
  { word: 'suceboules', category: 'insult' },
  { word: 'lèche-bourses', category: 'insult' },
  { word: 'leche-bourses', category: 'insult' },
  { word: 'lechebourses', category: 'insult' },
  { word: 'suceur', category: 'insult' },
  { word: 'suceurs', category: 'insult' },
  { word: 'suceuse', category: 'insult' },
  { word: 'suceuses', category: 'insult' },
  { word: 'tête de nœud', category: 'insult' },
  { word: 'tête de noeud', category: 'insult' },
  { word: 'tete de noeud', category: 'insult' },
  { word: 'tête de nœuds', category: 'insult' },
  { word: 'tete de noeuds', category: 'insult' },
  { word: 'tête de con', category: 'insult' },
  { word: 'tete de con', category: 'insult' },
  { word: 'têtes de con', category: 'insult' },
  { word: 'tetes de con', category: 'insult' },
  { word: 'tête de cul', category: 'insult' },
  { word: 'tete de cul', category: 'insult' },
  { word: 'tête de gland', category: 'insult' },
  { word: 'tete de gland', category: 'insult' },
  { word: 'gland', category: 'insult' },
  { word: 'glands', category: 'insult' },
  { word: 'glandeur', category: 'insult' },
  { word: 'glandeuse', category: 'insult' },
  { word: 'glandeurs', category: 'insult' },
  { word: 'glandeuses', category: 'insult' },
  { word: 'couillon', category: 'insult' },
  { word: 'couillons', category: 'insult' },
  { word: 'couillonne', category: 'insult' },
  { word: 'couillonnes', category: 'insult' },
  { word: 'crétiniser', category: 'insult' },
  { word: 'crétinisé', category: 'insult' },
  { word: 'abrutissement', category: 'insult' },
  { word: 'dégénéré', category: 'insult' },
  { word: 'degenere', category: 'insult' },
  { word: 'dégénérée', category: 'insult' },
  { word: 'degeneree', category: 'insult' },
  { word: 'dégénérés', category: 'insult' },
  { word: 'degeneres', category: 'insult' },
  { word: 'dégénérées', category: 'insult' },
  { word: 'degenerees', category: 'insult' },
  { word: 'degeneracy', category: 'insult' },
  { word: 'degenerate', category: 'insult' },
  { word: 'degenerates', category: 'insult' },
  { word: 'knobhead', category: 'insult' },
  { word: 'knobheads', category: 'insult' },
  { word: 'bell-end', category: 'insult' },
  { word: 'bell-ends', category: 'insult' },
  { word: 'ass-hole', category: 'insult' },
  { word: 'ass-holes', category: 'insult' },
  { word: 'cunt-face', category: 'insult' },
  { word: 'cuntface', category: 'insult' },
  { word: 'cunt-faces', category: 'insult' },
  { word: 'shit-head', category: 'insult' },
  { word: 'shit-heads', category: 'insult' },
  { word: 'dick-head', category: 'insult' },
  { word: 'dick-heads', category: 'insult' },
  { word: 'butt-head', category: 'insult' },
  { word: 'butthead', category: 'insult' },
  { word: 'butt-heads', category: 'insult' },
  { word: 'pecker', category: 'insult' },
  { word: 'peckers', category: 'insult' },
  { word: 'fuckhead', category: 'insult' },
  { word: 'fuckheads', category: 'insult' },
  { word: 'fuck-head', category: 'insult' },
  { word: 'fuck-heads', category: 'insult' },
  { word: 'fuckface', category: 'insult' },
  { word: 'fuck-face', category: 'insult' },
  { word: 'fuckfaces', category: 'insult' },
  { word: 'fuckwit', category: 'insult' },
  { word: 'fuckwits', category: 'insult' },
  { word: 'fuck-wit', category: 'insult' },
  { word: 'fuck-wits', category: 'insult' },
  { word: 'dip-shit', category: 'insult' },
  { word: 'dip-shits', category: 'insult' },
  { word: 'dumb-ass', category: 'insult' },
  { word: 'dumb-asses', category: 'insult' },
  { word: 'numbskull', category: 'insult' },
  { word: 'numbskulls', category: 'insult' },
  { word: 'bonehead', category: 'insult' },
  { word: 'boneheads', category: 'insult' },
  { word: 'airhead', category: 'insult' },
  { word: 'airheads', category: 'insult' },
  { word: 'sap', category: 'insult' },
  { word: 'saps', category: 'insult' },
  { word: 'dunderhead', category: 'insult' },
  { word: 'dunderheads', category: 'insult' },
  { word: 'blockhead', category: 'insult' },
  { word: 'blockheads', category: 'insult' },
  { word: 'nincompoop', category: 'insult' },
  { word: 'nincompoops', category: 'insult' },
  { word: 'rosbif', category: 'insult' },
  { word: 'rosbifs', category: 'insult' },
  { word: 'yankee', category: 'insult' },
  { word: 'yankees', category: 'insult' },
  { word: 'ricain', category: 'insult' },
  { word: 'ricains', category: 'insult' },
  { word: 'portougalais', category: 'insult' },
  { word: 'espagoing', category: 'insult' },
  { word: 'polak', category: 'insult' },
  { word: 'polaks', category: 'insult' },
  { word: 'youpin', category: 'insult' },
  { word: 'youpins', category: 'insult' },
  { word: 'youdi', category: 'insult' },
  { word: 'youdies', category: 'insult' },
  { word: 'feuj', category: 'insult' },
  { word: 'feujs', category: 'insult' },
  { word: 'rebeu', category: 'insult' },
  { word: 'rebeus', category: 'insult' },
  { word: 'renoi', category: 'insult' },
  { word: 'renois', category: 'insult' },
  { word: 'babtou', category: 'insult' },
  { word: 'babtous', category: 'insult' },
  { word: 'toubab', category: 'insult' },
  { word: 'toubabs', category: 'insult' },
  { word: 'gwer', category: 'insult' },
  { word: 'gwers', category: 'insult' },
  { word: 'kouffar', category: 'insult' },
  { word: 'kuffar', category: 'insult' },
  { word: 'koufr', category: 'insult' },
  { word: 'kuffr', category: 'insult' },
];

async function main() {

  // Ensure guild exists
  await prisma.guild.upsert({
    where: { id: guildId },
    update: {},
    create: { id: guildId },
  });

  console.log(`\n🌱 Seeding ${DEFAULT_DEVELOPER_EXCUSES.length} excuses développeur...`);

  let excusesCreated = 0;
  let excusesSkipped = 0;

  for (const excuse of DEFAULT_DEVELOPER_EXCUSES) {
    const existing = await prisma.developerExcuse.findFirst({ where: { text: excuse.text, language: 'fr' } });
    if (existing) {
      excusesSkipped++;
      continue;
    }

    await prisma.developerExcuse.create({
      data: {
        text: excuse.text,
        language: 'fr',
        category: excuse.category,
      },
    });
    excusesCreated++;
    console.log(`  ✅ ${excuse.text}`);
  }


  console.log(`\n🌱 Seeding ${DEFAULT_BANNED_WORDS.length} mots bannis globaux...`);

  let bannedWordsCreated = 0;
  let bannedWordsSkipped = 0;

  for (const item of DEFAULT_BANNED_WORDS) {
    const existing = await prisma.bannedWord.findFirst({
      where: {
        guildId: null,
        word: item.word,
      },
    });
    if (existing) {
      bannedWordsSkipped++;
      continue;
    }

    await prisma.bannedWord.create({
      data: {
        guildId: null,
        word: item.word,
        category: item.category,
        enabled: true,
      },
    });
    bannedWordsCreated++;
    console.log(`  ✅ [${item.category.toUpperCase()}] ${item.word}`);
  }

  console.log(`\n✨ Seed terminé : ${excusesCreated} excuses créées, ${excusesSkipped} excuses ignorées, ${bannedWordsCreated} mots bannis globaux créés, ${bannedWordsSkipped} ignorés`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
